import { useEffect, useMemo, useState } from 'react'
import { Area, Bar, BarChart, CartesianGrid, Cell, ComposedChart, Legend, Line, Pie, PieChart, ReferenceArea, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowDownRight, ArrowUpRight, ChevronDown, ChevronUp, Clock3, LockKeyhole, RefreshCw, Send, Sparkles, Trophy } from 'lucide-react'
import type { AnalyticsSnapshot, WorkspaceContext } from './model.js'
import { fetchAnalyticsInsights, queryAnalyticsInsights } from './api.js'
import { analyticsKpis, periodTrend } from './analytics-model.js'
import type { AnalyticsInsights, AnalyticsPeriod } from './analytics-model.js'
import { UpgradePlanButton } from './UpgradePlanButton.js'

const COLORS = ['#3b82f6', '#8b5cf6', '#14b8a6', '#f59e0b', '#ec4899', '#22c55e', '#06b6d4', '#f97316']
const FEATURE_NAMES: Readonly<Record<string, string>> = { anomaly_detection: 'Anomaly Detection', product_trends: 'Product Performance Trends', customer_segments: 'Customer Segment Analysis', natural_language_insight: 'AI Natural Language Insight', period_comparisons: 'Period Comparisons', geographic_distribution: 'Geographic Distribution', predictive_revenue: 'Predictive Revenue (Advanced)', cohort_analysis: 'Cohort Analysis', growth_opportunities: 'Growth Opportunity Detection', custom_ai_queries: 'Custom AI Analytics Queries', executive_report: 'Executive AI Report' }
export function AnalyticsPage({ context, snapshot, onSync, onNavigateBilling }: { context: WorkspaceContext; snapshot: AnalyticsSnapshot | null; onSync: (module: string) => Promise<void>; onNavigateBilling: () => void }) {
  const [insights, setInsights] = useState<AnalyticsInsights | null>(null); const [loading, setLoading] = useState(false); const [period, setPeriod] = useState<AnalyticsPeriod>(30); const [open, setOpen] = useState(true); const [question, setQuestion] = useState(''); const [answer, setAnswer] = useState(''); const [asking, setAsking] = useState(false)
  const refresh = () => { if (!context.storeId) return; setLoading(true); void fetchAnalyticsInsights(context.storeId).then(setInsights).finally(() => setLoading(false)) }
  useEffect(refresh, [context.storeId])
  const trend = useMemo(() => periodTrend(snapshot, period, insights?.forecast ?? null), [snapshot, period, insights]); const kpis = useMemo(() => analyticsKpis(snapshot, insights?.totalCustomers ?? null), [snapshot, insights]); const totalCategory = insights?.categories.reduce((sum, row) => sum + row.revenue, 0) ?? 0
  const ask = async () => { if (!context.storeId || !question.trim()) return; setAsking(true); try { const result = await queryAnalyticsInsights(context.storeId, question); setAnswer(result.text) } finally { setAsking(false) } }
  return <main className="analytics-page">
    <header className="analytics-page-header"><div><div className="section-kicker"><span className="kicker-dot blue" /> STORE PERFORMANCE</div><h1>Analytics</h1><p>AI-powered insights into your store performance</p></div><button className="button primary" onClick={() => void onSync('orders')}><RefreshCw size={14} className={loading ? 'spin' : ''} /> Refresh data</button></header>
    <section className="analytics-kpis">{kpis.map((kpi) => <KpiCard key={kpi.label} {...kpi} />)}</section>
    <section className="analytics-deep-dive">
      <article className="analytics-card revenue-trend"><header><div><span>Revenue deep dive</span><h2>Revenue Trend</h2></div><div className="period-toggle">{([7, 30, 90, 365] as const).map((days) => <button className={period === days ? 'active' : ''} onClick={() => setPeriod(days)} key={days}>{days === 365 ? '1y' : `${days}d`}</button>)}</div></header>
        {trend.length ? <div className="chart-large"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={trend} margin={{ top: 12, right: 14, left: -12, bottom: 0 }}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#3b82f6" stopOpacity=".4"/><stop offset="1" stopColor="#3b82f6" stopOpacity=".02"/></linearGradient><linearGradient id="forecastFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#8b5cf6" stopOpacity=".22"/><stop offset="1" stopColor="#8b5cf6" stopOpacity=".01"/></linearGradient></defs><CartesianGrid stroke="rgba(148,163,184,.11)" strokeDasharray="3 6" vertical={false}/><XAxis dataKey="day" tickFormatter={shortDay} tick={{ fill: '#718096', fontSize: 9 }} axisLine={false} tickLine={false} minTickGap={28}/><YAxis tickFormatter={compactMoney} tick={{ fill: '#718096', fontSize: 9 }} axisLine={false} tickLine={false}/><Tooltip content={<RevenueTooltip />}/><Bar dataKey="revenue" fill="#3b82f6" opacity={.13} radius={[3,3,0,0]} barSize={12}/><Area type="monotone" dataKey="revenue" fill="url(#revenueFill)" stroke="none"/><Line type="monotone" dataKey="previous" name="Previous period" stroke="#64748b" strokeDasharray="4 5" strokeWidth={1.5} dot={false} connectNulls={false}/><Area type="monotone" dataKey="forecast" fill="url(#forecastFill)" stroke="none" connectNulls={false}/><Line type="monotone" dataKey="revenue" name="Revenue" stroke="#60a5fa" strokeWidth={2.7} dot={{ r: 2.5, fill: '#bfdbfe', stroke: '#3b82f6', strokeWidth: 2 }} activeDot={{ r: 5 }} connectNulls={false}/><Line type="monotone" dataKey="forecast" name="Basic forecast" stroke="#a78bfa" strokeWidth={2} strokeDasharray="5 5" dot={{ r: 2 }} connectNulls={false}/></ComposedChart></ResponsiveContainer></div> : <Empty message="Sync orders to see your revenue trend." />}
        <footer><span><i className="legend-line actual" /> Actual</span><span><i className="legend-line previous" /> Previous period</span><span><i className="legend-line forecast" /> Basic forecast</span>{insights?.forecast.status === 'insufficient_data' && <small>{insights.forecast.message}</small>}</footer>
      </article>
      <article className="analytics-card category-card"><header><div><span>Revenue mix</span><h2>Sales by Category</h2></div></header>{insights?.categories.length ? <><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={insights.categories} dataKey="revenue" nameKey="name" innerRadius="60%" outerRadius="83%" paddingAngle={3}>{insights.categories.map((row, index) => <Cell key={row.name} fill={(COLORS[index % COLORS.length] ?? '#3b82f6')} />)}</Pie><Tooltip formatter={(value) => money(Number(value))}/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{money(totalCategory)}</strong><span>Total revenue</span></div></div><div className="category-legend">{insights.categories.map((row, index) => <div key={row.name}><i style={{ background: (COLORS[index % COLORS.length] ?? '#3b82f6') }} /><span>{row.name}</span><strong>{totalCategory ? `${(row.revenue / totalCategory * 100).toFixed(1)}%` : '—'}</strong><small>{money(row.revenue)}</small></div>)}</div></> : <Empty message="Product categories appear after product sales are synced." />}</article>
    </section>
    <section className={`analytics-card ai-analytics ${open ? '' : 'collapsed'}`}><header><div className="ai-title"><span><Sparkles size={18}/></span><div><small>SMART SIGNALS</small><h2>AI Analytics Intelligence</h2><p>Forecasts and store signals grounded in your synced sales.</p></div></div><div className="ai-actions">{insights && <UpgradePlanButton plan={insights.plan} onUpgrade={onNavigateBilling}/>}<button onClick={() => setOpen((value) => !value)} aria-label={open ? 'Collapse AI analytics' : 'Expand AI analytics'}>{open ? <ChevronUp size={16}/> : <ChevronDown size={16}/>}</button></div></header>{open && <div className="ai-body"><div className="ai-feature-grid"><article className="ai-feature basic"><span><ArrowUpRight size={16}/></span><div><small>AVAILABLE ON EVERY PLAN</small><h3>AI Sales Forecast</h3><p>{insights?.forecast.message ?? 'Loading forecast…'}</p><em>Basic forecast · upgrade for advanced AI</em></div></article><AnomalyCard insights={insights}/>{Object.entries(FEATURE_NAMES).filter(([feature]) => feature !== 'anomaly_detection').map(([feature, title]) => <FeatureCard key={feature} feature={feature} title={title} insights={insights} onUpgrade={onNavigateBilling}/>)}</div>{insights?.plan === 'commander' && <div className="analytics-query"><div><Sparkles size={15}/><span><strong>Ask your analytics</strong><small>Only aggregate, non-identifying store facts are sent.</small></span></div><div><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="What changed in my sales?"/><button onClick={() => void ask()} disabled={!question.trim() || asking}>{asking ? <RefreshCw className="spin" size={14}/> : <Send size={14}/>}</button></div>{answer && <p>{answer}</p>}</div>}</div>}</section>
    <section className="analytics-card top-products"><header><div><span>Revenue leaders</span><h2>Top Products by Revenue</h2></div></header>{insights?.topProducts.length ? <div className="top-products-scroll"><table><thead><tr><th>Rank</th><th>Product</th><th>Units sold</th><th>Revenue</th><th>% of total</th><th>Trend</th></tr></thead><tbody>{insights.topProducts.map((product, index) => <tr key={product.productId}><td><b className={index < 3 ? 'top-rank' : ''}>{index + 1}</b></td><td><div className="product-cell">{product.image ? <img src={product.image} alt=""/> : <span>{product.name.slice(0,1)}</span>}<strong>{product.name}</strong></div></td><td>{product.units.toLocaleString()}</td><td><strong>{money(product.revenue)}</strong></td><td>{product.share.toFixed(1)}%</td><td className={product.trend}>{product.trend === 'up' ? <ArrowUpRight size={15}/> : product.trend === 'down' ? <ArrowDownRight size={15}/> : '—'}</td></tr>)}</tbody></table></div> : <Empty message="Top products appear after product sales are synced." />}</section>
    <section className="patterns-grid"><article className="analytics-card pattern-card"><header><div><span>Weekly rhythm</span><h2>Best Performing Day</h2></div>{bestDay(insights) && <b><Trophy size={13}/>{bestDay(insights)?.day}</b>}</header>{insights?.weekdays.some((row) => row.revenue > 0) ? <div className="weekday-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={insights.weekdays}><CartesianGrid stroke="rgba(148,163,184,.09)" strokeDasharray="3 6" vertical={false}/><XAxis dataKey="day" tick={{ fill:'#718096', fontSize:9 }} axisLine={false} tickLine={false}/><YAxis tickFormatter={compactMoney} tick={{ fill:'#718096', fontSize:9 }} axisLine={false} tickLine={false}/><Tooltip formatter={(value) => money(Number(value))}/><Bar dataKey="revenue" radius={[5,5,0,0]}>{insights.weekdays.map((row) => <Cell key={row.day} fill={row.day === bestDay(insights)?.day ? '#60a5fa' : 'rgba(59,130,246,.3)'}/>)}</Bar></BarChart></ResponsiveContainer></div> : <Empty message="Awaiting daily sales history."/>}</article><article className="analytics-card pattern-card"><header><div><span>Shopping rhythm</span><h2>Peak Sales Hours</h2></div><Clock3 size={17}/></header>{insights?.peakHours ? <div className="hour-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={insights.peakHours}><XAxis dataKey="hour" tickFormatter={(hour) => `${hour}:00`} tick={{ fill:'#718096', fontSize:8 }} interval={3} axisLine={false}/><Tooltip labelFormatter={(hour) => `${hour}:00–${Number(hour)+1}:00`} /><Bar dataKey="orders" fill="#8b5cf6" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div> : <Empty message="Awaiting order-level timestamps."/>}</article></section>
  </main>
}
function KpiCard({ label, value, money: isMoney, change, sparkline }: ReturnType<typeof analyticsKpis>[number]) { const data = sparkline.map((amount, index) => ({ index, amount })); return <article className="analytics-kpi"><div><span>{label}</span><strong>{value === null ? '—' : isMoney ? money(value) : Math.round(value).toLocaleString()}</strong>{change === null ? <small>Comparison awaits prior-period data</small> : <small className={change >= 0 ? 'positive' : 'negative'}>{change >= 0 ? '▲' : '▼'} {Math.abs(change).toFixed(1)}% vs last 28 days</small>}</div><div className="sparkline">{data.length > 1 && <ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><Area type="monotone" dataKey="amount" stroke="#60a5fa" fill="rgba(59,130,246,.12)" strokeWidth={1.8}/></ComposedChart></ResponsiveContainer>}</div></article> }
function AnomalyCard({ insights }: { insights: AnalyticsInsights | null }) { const locked = insights?.locked.find((item) => item.feature === 'anomaly_detection'); if (locked) return <article className="ai-feature locked"><LockKeyhole size={16}/><div><small>START+</small><h3>Anomaly Detection</h3><p>Upgrade to spot unusual revenue spikes and dips.</p></div></article>; const anomalies = insights?.anomalies ?? []; return <article className="ai-feature"><Sparkles size={16}/><div><small>DETERMINISTIC SIGNAL</small><h3>Anomaly Detection</h3><p>{!insights ? 'Loading…' : insights.salesHistoryDays < 14 ? 'Need 14+ days for anomaly detection.' : anomalies.length ? `${anomalies[0]?.direction === 'spike' ? 'Revenue spike' : 'Revenue dip'} on ${anomalies[0]?.day} (${Math.abs(anomalies[0]?.percentFromAverage ?? 0).toFixed(0)}% vs average)` : 'No unusual revenue days detected.'}</p></div></article> }
function FeatureCard({ feature, title, insights, onUpgrade }: { feature: string; title: string; insights: AnalyticsInsights | null; onUpgrade: () => void }) { const locked = insights?.locked.find((item) => item.feature === feature); if (locked) return <button className="ai-feature locked" onClick={onUpgrade}><LockKeyhole size={16}/><div><small>{locked.requiredPlan.toUpperCase()}+</small><h3>{title}</h3><p>Upgrade to unlock this deeper analysis.</p></div></button>; return <article className="ai-feature"><Sparkles size={16}/><div><small>AVAILABLE</small><h3>{title}</h3><p>{feature === 'cohort_analysis' ? 'Built from your customer retention history.' : feature === 'custom_ai_queries' ? 'Ask questions using aggregate store facts.' : 'Ready when enough supporting sales history is available.'}</p></div></article> }
function RevenueTooltip({ active, payload, label }: { active?: boolean; payload?: readonly { name: string; value: number; color: string }[]; label?: string }) { if (!active || !payload?.length) return null; return <div className="analytics-tooltip"><strong>{label}</strong>{payload.filter((item) => item.value !== null).map((item) => <span key={item.name}><i style={{ background:item.color }}/>{item.name}: {money(item.value)}</span>)}</div> }
function Empty({ message }: { message: string }) { return <div className="analytics-empty"><Sparkles size={20}/><p>{message}</p></div> }
function bestDay(insights: AnalyticsInsights | null) { return insights?.weekdays.reduce((best, row) => row.revenue > best.revenue ? row : best, insights.weekdays[0] ?? { day:'', revenue:0 }) }
const money = (value: number) => new Intl.NumberFormat(undefined, { style:'currency', currency:'USD', maximumFractionDigits:value >= 1000 ? 0 : 2 }).format(value)
const compactMoney = (value: number) => `$${Intl.NumberFormat(undefined, { notation:'compact', maximumFractionDigits:1 }).format(value)}`
const shortDay = (value: string) => new Date(`${value}T00:00:00Z`).toLocaleDateString(undefined, { month:'short', day:'numeric', timeZone:'UTC' })
