import { Button } from './polaris-ui.js'
import { useEffect, useState } from 'react'
import { AlertTriangle, CheckCircle2, KeyRound, Pause, Play, RefreshCw, RotateCcw, Server, ShieldCheck } from './icons.js'
import { adminStepUp, fetchMaintenance, fetchMerchantFlags, fetchOpsMetrics, fetchOpsQueue, retryOpsJob, setMaintenance, setMerchantFlags } from './api.js'
import type { WorkspaceContext } from './model.js'
import type { MaintenanceState, MerchantFlags, OpsMetrics, QueueSnapshot } from './f9-model.js'

export function AdminOpsWorkspace({ context }: Readonly<{ context: WorkspaceContext }>) {
  const [key, setKey] = useState('')
  const [token, setToken] = useState<string | null>(null)
  const [maintenance, setMaintenanceState] = useState<MaintenanceState | null>(null)
  const [flags, setFlags] = useState<MerchantFlags | null>(null)
  const [queue, setQueue] = useState<QueueSnapshot | null>(null)
  const [metrics, setMetrics] = useState<OpsMetrics | null>(null)
  const [message, setMessage] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)
  const login = async () => { setBusy(true); try { const result = await adminStepUp(key); setToken(result.stepUpToken); setMessage('Admin step-up active for 15 minutes.') } catch (error: unknown) { setMessage(error instanceof Error ? error.message : 'Admin step-up failed.') } finally { setBusy(false) } }
  const refresh = async (stepUpToken = token) => { if (!stepUpToken) return; setBusy(true); try { const results = await Promise.all([fetchMaintenance(stepUpToken), fetchOpsQueue(stepUpToken), fetchOpsMetrics(stepUpToken), context.storeId ? fetchMerchantFlags(stepUpToken, context.storeId) : Promise.resolve(null)]); setMaintenanceState(results[0]); setQueue(results[1]); setMetrics(results[2]); setFlags(results[3]) } catch (error: unknown) { setMessage(error instanceof Error ? error.message : 'Admin ops refresh failed.') } finally { setBusy(false) } }
  useEffect(() => { if (token) void refresh(token) }, [token, context.storeId])
  const toggleMaintenance = async () => { if (!token || !maintenance) return; const next = await setMaintenance(token, { enabled: !maintenance.enabled, message: maintenance.message, expectedVersion: maintenance.version }); setMaintenanceState(next) }
  const updateFlags = async (patch: Partial<MerchantFlags>) => { if (!token || !flags) return; const next = await setMerchantFlags(token, { ...flags, ...patch }); setFlags(next) }
  const retry = async (id: string) => { if (!token) return; await retryOpsJob(token, id); await refresh(token) }
  if (!token) return <section className="f9-admin-login card"><span className="admin-icon"><KeyRound size={21} /></span><div><div className="section-kicker">F9 ADMIN OPERATIONS</div><h2>Step up to manage launch controls.</h2><p>Maintenance, merchant flags, queue retries, and metrics are protected by the existing admin step-up session.</p></div><label>Admin key<input type="password" value={key} onChange={(event) => setKey(event.target.value)} placeholder="Configured by deployment secret" /></label><Button className="button primary" onClick={() => void login()} disabled={busy || !key.trim()}><ShieldCheck size={15} /> {busy ? 'Checking…' : 'Start admin session'}</Button>{message && <div className="f9-message">{message}</div>}</section>
  return <div className="f9-ops"><div className="f9-ops-head"><div><div className="section-kicker">FINAL LAUNCH CONTROL PLANE</div><h2>Admin operations</h2><p>Critical endpoints remain exempt while merchant traffic can be paused safely.</p></div><Button className="button secondary" onClick={() => void refresh()} disabled={busy}><RefreshCw size={14} /> Refresh</Button></div><div className="f9-ops-grid"><section className={`card f9-maintenance ${maintenance?.enabled ? 'enabled' : ''}`}><div className="f9-card-title"><span><AlertTriangle size={16} /> Maintenance mode</span><span className={`status-badge ${maintenance?.enabled ? 'amber' : 'green'}`}>{maintenance?.enabled ? 'ON' : 'OFF'}</span></div><p>{maintenance?.message}</p><Button className="button secondary" onClick={() => void toggleMaintenance()}>{maintenance?.enabled ? <><Play size={14} /> Disable</> : <><Pause size={14} /> Enable</>}</Button><small>Health, webhooks, and admin routes stay available.</small></section><section className="card"><div className="f9-card-title"><span><ShieldCheck size={16} /> Merchant flags</span><span className="status-badge neutral">{flags?.storeId ?? 'No store'}</span></div>{flags ? <div className="f9-flag-list"><Flag label="AI features" value={flags.aiEnabled} onChange={(value) => void updateFlags({ aiEnabled: value })} /><Flag label="Automation" value={flags.automationEnabled} onChange={(value) => void updateFlags({ automationEnabled: value })} /><Flag label="Emergency suspend" value={!flags.suspended} onChange={(value) => void updateFlags({ suspended: !value })} /></div> : <span className="muted-cell">Open an embedded merchant workspace to manage its flags.</span>}</section></div><div className="f9-metric-strip"><Metric label="Queued" value={String(queue?.queued ?? '—')} /><Metric label="Processing" value={String(queue?.processing ?? '—')} /><Metric label="Failed" value={String(queue?.failed ?? '—')} /><Metric label="Dead-letter" value={String(queue?.deadLetter ?? '—')} /><Metric label="Active stores" value={String(metrics?.activeStores ?? '—')} /></div><section className="card f9-job-card"><div className="f9-card-title"><span><Server size={16} /> Live job queue</span><span className="mono">{queue?.queue ?? 'unavailable'}</span></div>{queue?.jobs.length ? queue.jobs.map((job) => <div className="f9-job-row" key={job.id}><span><strong>{job.type}</strong><small>{job.id} · {job.storeId} · attempts {job.attempts}</small></span><span className={`status-badge ${job.status === 'failed' || job.status === 'dead-letter' ? 'red' : job.status === 'completed' ? 'green' : 'neutral'}`}>{job.status}</span>{(job.status === 'failed' || job.status === 'dead-letter') && <Button className="button secondary" onClick={() => void retry(job.id)}><RotateCcw size={13} /> Retry</Button>}</div>) : <div className="f9-empty"><CheckCircle2 size={18} /> No queued or failed jobs reported.</div>}</section>{message && <div className="f9-message">{message}</div>}</div>
}
function Flag({ label, value, onChange }: Readonly<{ label: string; value: boolean; onChange: (value: boolean) => void }>) { return <label className="f9-flag"><span>{label}</span><Button type="button" className={`f9-toggle ${value ? 'on' : ''}`} aria-pressed={value} onClick={() => onChange(!value)}><i /></Button></label> }
function Metric({ label, value }: Readonly<{ label: string; value: string }>) { return <div className="f9-metric"><small>{label}</small><strong>{value}</strong></div> }
