import { deflateRawSync } from 'node:zlib'
import { AppError } from '@profitpilot/types'

export type ExportFormat = 'CSV' | 'XLSX' | 'PDF'
export type ExportRow = Readonly<Record<string, string | number | boolean | null>>
export type ExportFile = Readonly<{ filename: string; contentType: string; body: Buffer }>

export function writeCsv(filename: string, rows: readonly ExportRow[], columns?: readonly string[]): ExportFile { assertRows(rows); const keys = columns ?? Object.keys(rows[0] ?? {}); const lines = [keys.map(csvValue).join(',')]; for (const row of rows) lines.push(keys.map((key) => csvValue(row[key] ?? null)).join(',')); return { filename, contentType: 'text/csv; charset=utf-8', body: Buffer.from(`\ufeff${lines.join('\r\n')}\r\n`, 'utf8') } }

export function writeXlsx(filename: string, rows: readonly ExportRow[], columns?: readonly string[]): ExportFile { assertRows(rows); const keys = columns ?? Object.keys(rows[0] ?? {}); const sheetRows = [keys, ...rows.map((row) => keys.map((key) => row[key] ?? null))].map((row) => `<row>${row.map((value) => `<c t="inlineStr"><is><t>${xmlValue(value)}</t></is></c>`).join('')}</row>`).join(''); const files: Readonly<Record<string, string>> = { '[Content_Types].xml': '<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>', '_rels/.rels': '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>', 'xl/workbook.xml': '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Export" sheetId="1" r:id="rId1"/></sheets></workbook>', 'xl/_rels/workbook.xml.rels': '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>', 'xl/worksheets/sheet1.xml': `<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${sheetRows}</sheetData></worksheet>` }; return { filename, contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', body: zip(files) } }

export function writePdf(filename: string, rows: readonly ExportRow[], columns?: readonly string[]): ExportFile { assertRows(rows); const keys = columns ?? Object.keys(rows[0] ?? {}); const text = [keys.join(' | '), ...rows.map((row) => keys.map((key) => String(row[key] ?? '')).join(' | '))].join('\\n'); const objects = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Kids [3 0 R] /Count 1 >>', '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>', `<< /Length ${text.length + 43} >>\nstream\nBT /F1 9 Tf 36 740 Td (${pdfValue(text)}) Tj ET\nendstream`, '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>']; let body = '%PDF-1.4\n'; const offsets: number[] = [0]; for (let index = 0; index < objects.length; index += 1) { offsets.push(Buffer.byteLength(body, 'utf8')); body += `${index + 1} 0 obj\n${objects[index]}\nendobj\n` } const xref = Buffer.byteLength(body, 'utf8'); body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, '0')} 00000 n `).join('\n')}\ntrailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`; return { filename, contentType: 'application/pdf', body: Buffer.from(body, 'utf8') } }

function assertRows(rows: readonly ExportRow[]): void { if (rows.length > 50_000) throw new AppError('VALIDATION_ERROR', 'Exports are limited to 50,000 rows', 400, { rows: rows.length }) }
function csvValue(value: string | number | boolean | null): string { const text = value === null ? '' : String(value); return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text }
function xmlValue(value: string | number | boolean | null): string { return String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;') }
function pdfValue(value: string): string { return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)').replace(/\n/g, '\\n') }
function zip(files: Readonly<Record<string, string>>): Buffer { const chunks: Buffer[] = []; const central: Buffer[] = []; let offset = 0; for (const [name, text] of Object.entries(files)) { const data = Buffer.from(text, 'utf8'); const compressed = deflateRawSync(data); const crc = crc32(data); const local = Buffer.concat([Buffer.from([0x50,0x4b,0x03,0x04,20,0,0,0,8,0]), u16(crc), u16(crc >>> 16), u32(compressed.length), u32(data.length), u16(Buffer.byteLength(name)), Buffer.from([0,0]), Buffer.from(name), compressed]); chunks.push(local); central.push(Buffer.concat([Buffer.from([0x50,0x4b,0x01,0x02,20,0,20,0,8,0,0,0,0,0]), u16(crc), u16(crc >>> 16), u32(compressed.length), u32(data.length), u16(Buffer.byteLength(name)), Buffer.from([0,0,0,0,0,0,0,0]), u32(offset), Buffer.from(name)])); offset += local.length } const centralBuffer = Buffer.concat(central); return Buffer.concat([...chunks, centralBuffer, Buffer.from([0x50,0x4b,0x05,0x06,0,0,0,0]), u16(central.length), u16(central.length), u32(centralBuffer.length), u32(offset), Buffer.from([0,0])]) }
function u16(value: number): Buffer { const buffer = Buffer.alloc(2); buffer.writeUInt16LE(value & 0xffff); return buffer }
function u32(value: number): Buffer { const buffer = Buffer.alloc(4); buffer.writeUInt32LE(value >>> 0); return buffer }
function crc32(buffer: Buffer): number { let crc = 0xffffffff; for (const byte of buffer) { crc ^= byte; for (let bit = 0; bit < 8; bit += 1) crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1)) } return (crc ^ 0xffffffff) >>> 0 }