/**
 * Single source of truth for the Shopify access scopes ProfitPilot requests.
 *
 * Every scope declaration in the repository (.env.example, the OAuth install
 * URL built in bootstrap.ts, the generated shopify.app.toml, and the checked-in
 * docs/app-store/shopify.app.toml.template) is derived from — or verified
 * against — this list, so a stale copy can no longer drift out of sync.
 *
 * Why each scope exists:
 * - read_products / read_orders / read_customers: core analytics + sync.
 * - read_inventory / read_locations: inventory health and stockout features.
 * - read_discounts: reading discounts via the GraphQL Admin API.
 * - write_discounts: REQUIRED to run discountCodeBasicCreate and
 *   discountCodeDeactivate from the AI Command Center and Automation Engine.
 *   These are GraphQL mutations — the legacy `write_price_rules` REST scope
 *   does not authorize them, so Shopify answers with 403 Access Denied.
 * - read_price_rules: still required by the REST discounts sync module
 *   (/admin/api/.../price_rules.json in packages/sync). It reads legacy price
 *   rules and is unrelated to the GraphQL discount mutations above.
 *
 * `read_checkouts` was dropped: Shopify deprecated and shut down the REST
 * Checkout API (and its `read_checkouts` scope) in 2025, so it no longer
 * authorizes anything ProfitPilot calls.
 *
 * NOTE: this module is imported directly by scripts/generate-shopify-app-toml.ts
 * through Node's type stripping, so it must stay dependency-free (no imports).
 */
export const PROFITPILOT_SHOPIFY_SCOPES = [
  'read_products',
  'read_orders',
  'read_customers',
  'read_inventory',
  'read_locations',
  'read_discounts',
  'write_discounts',
  'read_price_rules',
] as const

/** Comma-separated form used by SHOPIFY_SCOPES and the `access_scopes` TOML field. */
export const PROFITPILOT_SHOPIFY_SCOPES_CSV: string = PROFITPILOT_SHOPIFY_SCOPES.join(',')

/**
 * Webhook topics ProfitPilot subscribes to via `[[webhooks.subscriptions]]`
 * in shopify.app.toml. Single source of truth: the checked-in
 * `docs/app-store/shopify.app.toml.template` and the TOML generated by
 * `scripts/generate-shopify-app-toml.ts` both derive from this list.
 *
 * - `app/uninstalled` is the mandatory app-lifecycle webhook (token
 *   revocation on uninstall).
 * - The remaining six topics are the Shopify events the Automation Engine
 *   can trigger on: `automation.triggers.handleWebhook` matches workflow
 *   triggers by topic, so a workflow built on one of these fires in
 *   production.
 *
 * `checkouts/*` and `carts/*` are intentionally NOT subscribed: Shopify
 * deprecated those topics alongside the REST Checkout API, so a subscription
 * would never deliver a payload.
 */
export const PROFITPILOT_WEBHOOK_TOPICS = [
  'app/uninstalled',
  'orders/create',
  'orders/updated',
  'customers/create',
  'customers/update',
  'products/update',
  'inventory_levels/update',
] as const

/**
 * Normalize a comma-separated scope string into the effective scope list.
 *
 * The required registry is always included: an operator whose SHOPIFY_SCOPES
 * value predates a new capability (for example a deployment still requesting
 * only read_price_rules) would otherwise install the app without the
 * write_discounts scope and hit a 403 the first time a discount action runs.
 * Any extra scope supplied through the environment is preserved after the
 * required ones.
 */
export function parseShopifyScopes(value: string | undefined): readonly string[] {
  const requested = (value ?? '')
    .split(',')
    .map((scope) => scope.trim())
    .filter((scope) => scope.length > 0)
  const merged = new Set<string>(PROFITPILOT_SHOPIFY_SCOPES)
  for (const scope of requested) merged.add(scope)
  return [...merged]
}

/**
 * Scopes ProfitPilot needs that a Shopify installation did not grant. Empty
 * means the installation can run every feature, discount actions included.
 */
export function missingShopifyScopes(granted: readonly string[] | string | undefined): readonly string[] {
  const list = typeof granted === 'string' ? granted.split(',') : (granted ?? [])
  const present = new Set(list.map((scope) => scope.trim()).filter((scope) => scope.length > 0))
  return PROFITPILOT_SHOPIFY_SCOPES.filter((scope) => !present.has(scope))
}

export type ShopifyAppTomlConfig = Readonly<{
  clientId: string
  name: string
  applicationUrl: string
  redirectUrls: readonly string[]
  scopes: readonly string[]
  apiVersion: string
  privacyWebhookUrl: string
}>

export type AppStoreScreenshotSpec = Readonly<{ name: string; width: number; height: number; format: 'PNG' | 'JPG'; maxBytes: number; description: string }>

export const APP_STORE_SCREENSHOT_SPECS: readonly AppStoreScreenshotSpec[] = [
  { name: 'dashboard', width: 1600, height: 1000, format: 'PNG', maxBytes: 5_000_000, description: 'Store health and real-data sync state.' },
  { name: 'recommendations', width: 1600, height: 1000, format: 'PNG', maxBytes: 5_000_000, description: 'Evidence-backed recommendation review and approval.' },
  { name: 'automation', width: 1600, height: 1000, format: 'PNG', maxBytes: 5_000_000, description: 'Workflow safety gates and idempotent execution history.' },
  { name: 'billing', width: 1600, height: 1000, format: 'PNG', maxBytes: 5_000_000, description: 'Plan, usage, trial, and measurable ROI information.' },
]

export function shopifyAppConfigFromEnv(env: Readonly<Record<string, string | undefined>>): ShopifyAppTomlConfig {
  const applicationUrl = required(env, 'SHOPIFY_APP_URL', 'APP_URL')
  const clientId = required(env, 'SHOPIFY_API_KEY')
  const callback = env.SHOPIFY_REDIRECT_URI?.trim() || `${applicationUrl.replace(/\/$/, '')}/shopify/callback`
  // Never empty and never partial: parseShopifyScopes merges SHOPIFY_SCOPES
  // with the required registry, so the generated TOML always declares the full
  // set of scopes the app actually calls.
  const scopes = parseShopifyScopes(env.SHOPIFY_SCOPES)
  const privacyWebhookUrl = env.SHOPIFY_PRIVACY_WEBHOOK_URL?.trim() || `${applicationUrl.replace(/\/$/, '')}/shopify/webhooks`
  return { clientId, name: env.SHOPIFY_APP_NAME?.trim() || 'ProfitPilot', applicationUrl, redirectUrls: [callback], scopes, apiVersion: env.SHOPIFY_API_VERSION?.trim() || '2026-07', privacyWebhookUrl }
}

/** Mandatory Shopify GDPR compliance topics. The TOML `compliance_topics`
 *  subscription is the ONLY registration channel for these: the Partner
 *  Dashboard has no UI for them and the Admin API cannot subscribe to them. */
export const PROFITPILOT_COMPLIANCE_TOPICS = ['customers/data_request', 'customers/redact', 'shop/redact'] as const

export function renderShopifyAppToml(config: ShopifyAppTomlConfig): string {
  const redirects = config.redirectUrls.map((url) => `  "${tomlEscape(url)}"`).join(',\n')
  // The Shopify CLI rejects relative webhook URIs, so both subscription
  // blocks use the absolute https URL derived from the app host.
  const webhookUrl = config.privacyWebhookUrl
  const webhookTopics = PROFITPILOT_WEBHOOK_TOPICS.map((topic) => `"${tomlEscape(topic)}"`).join(', ')
  const complianceTopics = PROFITPILOT_COMPLIANCE_TOPICS.map((topic) => `"${tomlEscape(topic)}"`).join(', ')
  // Regular `topics` and GDPR `compliance_topics` must live in SEPARATE
  // [[webhooks.subscriptions]] blocks — the CLI schema does not allow mixing
  // them, and the obsolete [webhooks.privacy] table no longer exists.
  return `client_id = "${tomlEscape(config.clientId)}"\nname = "${tomlEscape(config.name)}"\napplication_url = "${tomlEscape(config.applicationUrl)}"\nembedded = true\n\n[build]\nautomatically_update_urls_on_dev = true\n\n[auth]\nredirect_urls = [\n${redirects}\n]\n\n[access_scopes]\nscopes = "${tomlEscape(config.scopes.join(','))}"\n\n[webhooks]\napi_version = "${tomlEscape(config.apiVersion)}"\n\n[[webhooks.subscriptions]]\ntopics = [${webhookTopics}]\nuri = "${tomlEscape(webhookUrl)}"\n\n[[webhooks.subscriptions]]\ncompliance_topics = [${complianceTopics}]\nuri = "${tomlEscape(webhookUrl)}"\n`
}

export type AppListingMetadata = Readonly<{
  name: string
  tagline: string
  category: string
  description: string
  supportEmail: string
  supportUrl: string
  privacyPolicyUrl: string
  termsOfServiceUrl: string
  securityPolicyUrl: string
  cookiePolicyUrl: string
  dataProcessingAddendumUrl: string
  complianceLinks: readonly string[]
}>

/**
 * Listing metadata with absolute HTTPS URLs. The Shopify Partner Dashboard
 * requires absolute policy/support URLs, so every legal link is resolved
 * against the configured app host (`SHOPIFY_APP_URL`, falling back to
 * `APP_URL`). `SUPPORT_URL` may override the support destination (defaults to
 * `<app host>/support`); `SUPPORT_EMAIL` stays available for email footers.
 */
export function appListingMetadata(env: Readonly<Record<string, string | undefined>> = process.env): AppListingMetadata {
  const configured = env.SHOPIFY_APP_URL?.trim() || env.APP_URL?.trim() || ''
  // Never fall back to a fake production host: broken privacy/terms/support
  // links are an App Store rejection. Production refuses to serve listing
  // metadata without a configured app URL; development gets a clearly-marked
  // local URL plus a warning.
  if (!configured && (env.NODE_ENV?.trim() || 'development') === 'production') {
    throw new Error('SHOPIFY_APP_URL (or APP_URL) must be configured in production — app listing legal/support URLs cannot be generated without it')
  }
  // Dev-only notice. This module must stay dependency-free (see header note),
  // so it uses process.emitWarning instead of @profitpilot/logger.
  if (!configured) process.emitWarning('SHOPIFY_APP_URL/APP_URL is not set; using the development placeholder https://localhost:3000 for listing URLs', { code: 'PROFITPILOT_APP_URL_UNSET' })
  const appUrl = (configured || 'https://localhost:3000').replace(/\/+$/, '')
  const supportUrl = (env.SUPPORT_URL?.trim() || `${appUrl}/support`).replace(/\/+$/, '')
  const supportEmail = env.SUPPORT_EMAIL?.trim() || ''
  const legalPath = (path: string): string => `${appUrl}${path}`
  const privacyPolicyUrl = legalPath('/legal/privacy')
  const termsOfServiceUrl = legalPath('/legal/terms')
  const securityPolicyUrl = legalPath('/legal/security')
  const cookiePolicyUrl = legalPath('/legal/cookies')
  const dataProcessingAddendumUrl = legalPath('/legal/dpa')
  return {
    name: 'ProfitPilot',
    tagline: 'A review-first AI employee for Shopify operations.',
    category: 'Store management',
    description: 'ProfitPilot monitors authorized Shopify data, explains deterministic opportunities, requests merchant approval, executes approved workflows, and measures outcomes. It does not invent store numbers and it minimizes customer personal data before optional language-model explanations.',
    supportEmail,
    supportUrl,
    privacyPolicyUrl,
    termsOfServiceUrl,
    securityPolicyUrl,
    cookiePolicyUrl,
    dataProcessingAddendumUrl,
    complianceLinks: [privacyPolicyUrl, termsOfServiceUrl, securityPolicyUrl, cookiePolicyUrl, dataProcessingAddendumUrl],
  }
}

function required(env: Readonly<Record<string, string | undefined>>, primary: string, fallback?: string): string {
  const value = env[primary]?.trim() || (fallback ? env[fallback]?.trim() : undefined)
  if (!value) throw new Error(`Missing required Shopify app environment variable ${primary}`)
  return value
}

function tomlEscape(value: string): string {
  return value.replaceAll('\\', '\\\\').replaceAll('"', '\\"').replaceAll('\n', '\\n')
}
