import { randomUUID } from 'node:crypto'
import { Router } from 'express'
import type { Request } from 'express'
import { AppError, requestId, storeId, success } from '@profitpilot/types'
import { activateWorkflow, compileTemplate, MerchantEmailVerifier, priorityForPlan, ThreadLedger } from '@profitpilot/automation'
import type { CampaignTemplate, MerchantEmailConfigRepository, TemplateRepository, Ticket, WorkflowDefinition, WorkflowRepository } from '@profitpilot/automation'
import type { TargetedCampaignInput, TargetedCampaignService } from './targeted-campaigns.js'
import { writeCsv, writePdf, writeXlsx } from '@profitpilot/reporting'
import type { ExportRow, ExportFormat } from '@profitpilot/reporting'

export type AutomationRouteDependencies = Readonly<{ workflows: WorkflowRepository; templates: TemplateRepository; emailVerifier: MerchantEmailVerifier; merchantEmails?: MerchantEmailConfigRepository; targetedCampaigns?: Pick<TargetedCampaignService, 'preview' | 'send' | 'unsubscribe'>; tickets: ThreadLedger; exportRows?: (storeId: string, dataset: 'orders' | 'catalog' | 'audit' | 'revenue') => Promise<readonly import('@profitpilot/reporting').ExportRow[]> }>

export function createAutomationRouter(dependencies: AutomationRouteDependencies): Router {
  const router = Router()
  router.get('/automation/workflows', async (request, response, next) => { try { response.status(200).json(success(await dependencies.workflows.list(queryStore(request)), requestIdFrom(request))) } catch (error: unknown) { if (isMissingRelation(error)) { response.status(200).json(success([], requestIdFrom(request))); return } next(error) } })
  router.post('/automation/workflows', async (request, response, next) => { try { const definition = request.body as WorkflowDefinition; await dependencies.workflows.put(definition); response.status(201).json(success(definition, requestIdFrom(request))) } catch (error: unknown) { next(error) } })
  router.post('/automation/workflows/:id/activate', async (request, response, next) => { try { const draft = await dependencies.workflows.get(request.params.id); if (!draft) throw new AppError('NOT_FOUND', 'Workflow not found', 404); const activated = activateWorkflow(draft, new Date().toISOString()); await dependencies.workflows.activate(activated); response.status(200).json(success(activated, requestIdFrom(request))) } catch (error: unknown) { next(error) } })
  router.get('/campaigns/templates', async (request, response, next) => { try { const tenant = queryStore(request); response.status(200).json(success(await dependencies.templates.list(tenant), requestIdFrom(request))) } catch (error: unknown) { next(error) } })
  router.post('/campaigns/templates', async (request, response, next) => { try { const body = request.body as unknown; if (!isRecord(body) || typeof body.storeId !== 'string') throw new AppError('VALIDATION_ERROR', 'storeId is required for campaign templates', 400); const template = compileTemplate(body as Omit<CampaignTemplate, 'variables'>); await dependencies.templates.put(template); response.status(201).json(success(template, requestIdFrom(request))) } catch (error: unknown) { next(error) } })
  router.post('/campaigns/preview', async (request, response, next) => { try { if (!dependencies.targetedCampaigns) throw new AppError('DEPENDENCY_ERROR', 'Targeted campaign delivery is unavailable', 503); const input = targetedInput(request.body, false); response.status(200).json(success(await dependencies.targetedCampaigns.preview(input), requestIdFrom(request))) } catch (error: unknown) { next(error) } })
  router.post('/campaigns/send', async (request, response, next) => { try { if (!dependencies.targetedCampaigns) throw new AppError('DEPENDENCY_ERROR', 'Targeted campaign delivery is unavailable', 503); const input = targetedInput(request.body, true); response.status(200).json(success(await dependencies.targetedCampaigns.send(input), requestIdFrom(request))) } catch (error: unknown) { next(error) } })
  router.get('/campaigns/unsubscribe', async (request, response, next) => { try { if (!dependencies.targetedCampaigns) throw new AppError('DEPENDENCY_ERROR', 'Campaign unsubscribe is unavailable', 503); const token = typeof request.query.token === 'string' ? request.query.token : ''; const result = await dependencies.targetedCampaigns.unsubscribe(token); response.status(200).type('html').send(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Unsubscribed</title></head><body><main><h1>You are unsubscribed</h1><p>${result.alreadySuppressed ? 'This email was already unsubscribed.' : 'Marketing email for this store has been disabled.'}</p></main></body></html>`) } catch (error: unknown) { next(error) } })
  router.post('/exports', async (request, response, next) => { try { const body = request.body as unknown; if (!isRecord(body) || !isFormat(body.format)) throw new AppError('VALIDATION_ERROR', 'format is required', 400); const dataset = isDataset(body.dataset) ? body.dataset : null; const supplied = Array.isArray(body.rows) ? body.rows.filter(isExportRow) : []; const storeId = typeof body.storeId === 'string' ? body.storeId : typeof request.query.storeId === 'string' ? request.query.storeId : ''; const rows = dataset && dependencies.exportRows && storeId ? await dependencies.exportRows(storeId, dataset) : supplied; const file = body.format === 'CSV' ? writeCsv(`${dataset ?? 'export'}-${randomUUID()}.csv`, rows) : body.format === 'XLSX' ? writeXlsx(`${dataset ?? 'export'}-${randomUUID()}.xlsx`, rows) : writePdf(`${dataset ?? 'export'}-${randomUUID()}.pdf`, rows); response.status(200).json(success({ filename: file.filename, contentType: file.contentType, bodyBase64: file.body.toString('base64'), rows: rows.length, ceiling: 50_000, ceilingNote: 'Technical safety limit for one file — not a plan quota.' }, requestIdFrom(request))) } catch (error: unknown) { next(error) } })
  router.get('/support/tickets', (request, response) => response.status(200).json(success(dependencies.tickets.list(queryStore(request)), requestIdFrom(request))))
  router.post('/support/tickets', (request, response, next) => { try { const body = request.body as unknown; if (!isRecord(body) || typeof body.shopId !== 'string' || typeof body.subject !== 'string' || !isPlan(body.plan)) throw new AppError('VALIDATION_ERROR', 'shopId, subject, and plan are required', 400); const now = Date.now(); const priority = body.priority === 'NORMAL' || body.priority === 'HIGH' || body.priority === 'URGENT' ? body.priority : priorityForPlan(body.plan); const ticket: Ticket = { id: randomUUID(), shopId: body.shopId, subject: body.subject.trim().slice(0, 200) || 'Support request', description: typeof body.description === 'string' ? body.description.trim().slice(0, 4_000) : '', priority, status: 'OPEN', createdAt: now, updatedAt: now, version: 0 }; response.status(201).json(success(dependencies.tickets.create(ticket), requestIdFrom(request))) } catch (error: unknown) { next(error) } })
  router.post('/settings/merchant-email', async (request, response, next) => { try { const body = request.body as unknown; if (!isRecord(body) || typeof body.shopId !== 'string' || typeof body.email !== 'string' || typeof body.fromName !== 'string') throw new AppError('VALIDATION_ERROR', 'shopId, email, and fromName are required', 400); const saved = dependencies.emailVerifier.save(body.shopId, body.email, body.fromName); const config = { ...saved, verificationSentAt: Date.now() }; dependencies.emailVerifier.hydrate(config); await dependencies.merchantEmails?.put(config); const verificationToken = dependencies.emailVerifier.token(body.shopId, body.email, Date.now() + 86_400_000); response.status(200).json(success({ config, verificationRequired: true, verificationToken }, requestIdFrom(request))) } catch (error: unknown) { next(error) } })
  router.post('/settings/merchant-email/verify', async (request, response, next) => { try { const body = request.body as unknown; if (!isRecord(body) || typeof body.token !== 'string') throw new AppError('VALIDATION_ERROR', 'verification token is required', 400); const claimedStore = body.token.split('|')[0] ?? ''; if (claimedStore && dependencies.merchantEmails) { const durable = await dependencies.merchantEmails.get(claimedStore); if (durable) dependencies.emailVerifier.hydrate(durable) }; const config = dependencies.emailVerifier.verify(body.token); await dependencies.merchantEmails?.put(config); response.status(200).json(success(config, requestIdFrom(request))) } catch (error: unknown) { next(error) } })
  return router
}

function queryStore(request: Request): string { const value = request.query.storeId; if (typeof value !== 'string' || !value.trim()) throw new AppError('VALIDATION_ERROR', 'storeId is required', 400); return value }
function targetedInput(value: unknown, requireReview: boolean): TargetedCampaignInput {
  if (!isRecord(value) || typeof value.storeId !== 'string' || typeof value.customerId !== 'string' || typeof value.templateId !== 'string' || typeof value.idempotencyKey !== 'string') throw new AppError('VALIDATION_ERROR', 'storeId, customerId, templateId, and idempotencyKey are required', 400)
  for (const forbidden of ['email', 'recipientEmail', 'acceptsMarketing', 'marketingState', 'phone']) if (forbidden in value) throw new AppError('VALIDATION_ERROR', `Client-supplied ${forbidden} is not accepted`, 400)
  if (requireReview && value.reviewed !== true) throw new AppError('VALIDATION_ERROR', 'Explicit merchant review is required', 400)
  return { storeId: storeId(value.storeId), customerId: value.customerId, templateId: value.templateId, idempotencyKey: value.idempotencyKey, reviewed: value.reviewed === true }
}
function requestIdFrom(request: Request) { return requestId(request.header('x-request-id') || randomUUID()) }
function isFormat(value: unknown): value is ExportFormat { return value === 'CSV' || value === 'XLSX' || value === 'PDF' }
function isDataset(value: unknown): value is 'orders' | 'catalog' | 'audit' | 'revenue' { return value === 'orders' || value === 'catalog' || value === 'audit' || value === 'revenue' }
function isMissingRelation(error: unknown): boolean { return error instanceof Error && /relation .* does not exist/i.test(error.message) }
function isPlan(value: unknown): value is 'start' | 'growth' | 'commander' { return value === 'start' || value === 'growth' || value === 'commander' }
function isRecord(value: unknown): value is Readonly<Record<string, unknown>> { return typeof value === 'object' && value !== null && !Array.isArray(value) }
function isExportRow(value: unknown): value is ExportRow { return isRecord(value) && Object.values(value).every((item) => item === null || typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean') }
