import { createServer } from 'node:http'
import { describe, expect, it } from 'vitest'
import { InMemoryTemplateRepository, InMemoryWorkflowRepository, MerchantEmailVerifier, ThreadLedger } from '@profitpilot/automation'
import { Logger } from '@profitpilot/logger'
import { createApi } from './app.js'

async function withServer<T>(handler: (base: string) => Promise<T>): Promise<T> { const app = createApi({ logger: new Logger(), readinessChecks: [], automation: { workflows: new InMemoryWorkflowRepository(), templates: new InMemoryTemplateRepository(), emailVerifier: new MerchantEmailVerifier('secret'), tickets: new ThreadLedger() } }); const server = createServer(app); await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve)); const address = server.address(); if (!address || typeof address === 'string') throw new Error('No address'); try { return await handler(`http://127.0.0.1:${address.port}`) } finally { await new Promise<void>((resolve) => server.close(() => resolve())) } }

const definition = { id: 'wf', storeId: 's', version: 1, nodes: [{ id: 'trigger', type: 'trigger', config: { trigger: 'manual' }, next: ['action'] }, { id: 'action', type: 'action', config: { action: 'tag' }, next: [] }] }

describe('F6 automation and marketing APIs', () => {
  it('creates and activates a workflow', async () => await withServer(async (base) => { const created = await fetch(`${base}/automation/workflows`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(definition) }); expect(created.status).toBe(201); const activated = await fetch(`${base}/automation/workflows/wf/activate`, { method: 'POST' }); expect(activated.status).toBe(200) }))
  it('lists workflow drafts by store', async () => await withServer(async (base) => { await fetch(`${base}/automation/workflows`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(definition) }); expect((await (await fetch(`${base}/automation/workflows?storeId=s`)).json()).data).toHaveLength(1) }))
  it('compiles campaign templates and rejects invalid variables', async () => await withServer(async (base) => { const response = await fetch(`${base}/campaigns/templates`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: 't', storeId: 's', name: 'Welcome', kind: 'EMAIL', subject: 'Hi {{customer.first_name}}', body: 'Bye {{unsubscribe.url}}' }) }); expect(response.status).toBe(201); const invalid = await fetch(`${base}/campaigns/templates`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: 'bad', storeId: 's', name: 'Bad', kind: 'EMAIL', subject: 'Hi {{bad}}', body: 'No {{unsubscribe.url}}' }) }); expect(invalid.status).toBe(400) }))
  it('exports real rows with the selected writer', async () => await withServer(async (base) => { const response = await fetch(`${base}/exports`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ format: 'CSV', rows: [{ id: 1, name: 'A' }] }) }); expect(response.status).toBe(200); expect((await response.json()).data.contentType).toContain('csv') }))
  it('creates tickets with plan priority', async () => await withServer(async (base) => { const response = await fetch(`${base}/support/tickets`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ shopId: 's', subject: 'Help', plan: 'commander' }) }); expect(response.status).toBe(201); expect((await response.json()).data.priority).toBe('URGENT') }))
  it('verifies merchant email settings before campaign use', async () => await withServer(async (base) => { const saved = await fetch(`${base}/settings/merchant-email`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ shopId: 's', email: 'merchant@example.com', fromName: 'Store' }) }); const token = (await saved.json()).data.verificationToken as string; const verified = await fetch(`${base}/settings/merchant-email/verify`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ token }) }); expect(verified.status).toBe(200) }))
})
