import type { QueryResultRow, SqlExecutor } from '@profitpilot/db'
import { withTenantContext } from '@profitpilot/db'
import type { AutomationExecutionService, WorkflowRecord, WorkflowRepository } from '@profitpilot/automation'
import type { WebhookEvent } from '@profitpilot/shopify'

export class AutomationTriggerService {
  public constructor(private readonly database:SqlExecutor,private readonly workflows:WorkflowRepository,private readonly execution:AutomationExecutionService){}
  public async handleWebhook(event:WebhookEvent):Promise<number>{const page=await this.workflows.list(event.storeId,{status:'ACTIVE',limit:50});let matched=0;for(const workflow of page.items){if(!workflow.enabled)continue;const trigger=workflow.nodes.find(node=>node.type==='trigger');if(trigger?.config.trigger!=='shopify_webhook'||trigger.config.topic!==event.topic||!workflow.definitionHash||!workflow.activatedAt)continue;let context:Readonly<Record<string,unknown>>={};try{const parsed:unknown=JSON.parse(event.rawBody);if(typeof parsed==='object'&&parsed!==null&&!Array.isArray(parsed))context=parsed as Readonly<Record<string,unknown>>}catch{/* verified webhook can still have a non-object payload */}const run=await this.execution.start({...workflow,definitionHash:workflow.definitionHash,activatedAt:workflow.activatedAt},{triggerType:'SHOPIFY_WEBHOOK',triggerEventId:event.webhookId,context});void this.execution.execute({...workflow,definitionHash:workflow.definitionHash,activatedAt:workflow.activatedAt},run.id);matched+=1}return matched}
  public async tickSchedules(now=new Date()):Promise<number>{const stores=await this.database.query<QueryResultRow&{id:string}>('SELECT id FROM stores ORDER BY id');const due:Array<QueryResultRow&{id:string;store_id:string;definition:WorkflowRecord;definition_hash:string;activated_at:Date;timezone:string}>=[];for(const store of stores.rows){if(due.length>=100)break;const result=await withTenantContext(this.database,store.id,async client=>client.query<QueryResultRow&{id:string;store_id:string;definition:WorkflowRecord;definition_hash:string;activated_at:Date;timezone:string}>(`SELECT id,store_id,definition,definition_hash,activated_at,timezone FROM workflows WHERE store_id=$1 AND status='ACTIVE' AND enabled AND definition->'nodes' @> '[{"type":"trigger","config":{"trigger":"cron"}}]'::jsonb AND (next_run_at IS NULL OR next_run_at<=$2) ORDER BY next_run_at NULLS FIRST LIMIT $3`,[store.id,now,100-due.length]));due.push(...result.rows)}let count=0;for(const row of due){const workflow=await this.workflows.get(row.store_id,row.id);if(!workflow?.definitionHash||!workflow.activatedAt)continue;const trigger=workflow.nodes.find(node=>node.type==='trigger');const cron=typeof trigger?.config.cron==='string'?trigger.config.cron:null;if(!cron)continue;const run=await this.execution.start({...workflow,definitionHash:workflow.definitionHash,activatedAt:workflow.activatedAt},{triggerType:'SCHEDULED',triggerEventId:`schedule:${row.id}:${now.toISOString()}`,context:{scheduledAt:now.toISOString()}});void this.execution.execute({...workflow,definitionHash:workflow.definitionHash,activatedAt:workflow.activatedAt},run.id);const next=nextCron(cron,now,workflow.timezone||'UTC');await withTenantContext(this.database,row.store_id,async client=>{await client.query('UPDATE workflows SET next_run_at=$3 WHERE store_id=$1 AND id=$2',[row.store_id,row.id,next])});count+=1}return count}
  public async purgeExpiredData():Promise<number>{const stores=await this.database.query<QueryResultRow&{id:string}>('SELECT id FROM stores ORDER BY id');let purged=0;for(const store of stores.rows){purged+=await withTenantContext(this.database,store.id,async client=>{const result=await client.query(`UPDATE workflow_steps s SET input='{"purged":true}'::jsonb,output='{"purged":true}'::jsonb,updated_at=now() FROM workflow_runs r WHERE s.store_id=$1 AND r.store_id=s.store_id AND r.id=s.run_id AND r.created_at<now()-interval '30 days' AND (s.input<>'{"purged":true}'::jsonb OR s.output<>'{"purged":true}'::jsonb)`,[store.id]);await client.query(`UPDATE workflow_approvals SET status='EXPIRED',decided_at=now(),decision_reason='Approval expired' WHERE store_id=$1 AND status='PENDING' AND expires_at<=now()`,[store.id]);return result.rowCount})}return purged}
  public resumeWaits(){return this.execution.resumeDue(async(store,id)=>{const workflow=await this.workflows.get(store,id);return workflow?.definitionHash&&workflow.activatedAt?{...workflow,definitionHash:workflow.definitionHash,activatedAt:workflow.activatedAt}:null})}
}
function nextCron(expression:string,after:Date,timezone:string):Date{const fields=expression.trim().split(/\s+/);const [minute='*',hour='*',day='*',month='*',weekday='*']=fields;const formatter=new Intl.DateTimeFormat('en-US',{timeZone:timezone,minute:'numeric',hour:'numeric',hourCycle:'h23',day:'numeric',month:'numeric',weekday:'short'});const week:Readonly<Record<string,number>>={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6};for(let offset=1;offset<=366*24*60;offset+=1){const date=new Date(after.getTime()+offset*60_000);const parts=Object.fromEntries(formatter.formatToParts(date).map(part=>[part.type,part.value]));if(matches(minute,Number(parts.minute))&&matches(hour,Number(parts.hour))&&matches(day,Number(parts.day))&&matches(month,Number(parts.month))&&matches(weekday,week[parts.weekday??'']??-1))return date}throw new Error('Cron schedule does not produce a run within one year')}
function matches(field:string,value:number):boolean{if(field==='*')return true;if(field.startsWith('*/'))return value%Number(field.slice(2))===0;return field.split(',').some(part=>part.includes('-')?(()=>{const[start,end]=part.split('-').map(Number);return value>=(start??0)&&value<=(end??0)})():Number(part)===value)}
