import type { QueryResultRow, SqlExecutor } from '@profitpilot/db'
import type { ControlAuditEvent, F9ControlRepository, MaintenanceState, MerchantFlags } from '@profitpilot/monitoring'

type MaintenanceRow = QueryResultRow & { maintenance_enabled: boolean; maintenance_message: string; version: number; updated_by: string; updated_at: Date }
type FlagRow = QueryResultRow & { store_id: string; ai_enabled: boolean; automation_enabled: boolean; suspended: boolean; version: number; updated_by: string; updated_at: Date }
type AuditRow = QueryResultRow & { id: string; store_id: string | null; actor_id: string; action: ControlAuditEvent['action']; before_state: unknown; after_state: unknown; created_at: Date }

export class PostgresF9ControlRepository implements F9ControlRepository {
  private readonly executor: SqlExecutor
  public constructor(executor: SqlExecutor) { this.executor = executor }
  public async getMaintenance(): Promise<MaintenanceState> { const result = await this.executor.query<MaintenanceRow>('SELECT maintenance_enabled, maintenance_message, version, updated_by, updated_at FROM platform_controls WHERE id = true LIMIT 1'); const row = result.rows[0]; return row ? { enabled: row.maintenance_enabled, message: row.maintenance_message, version: row.version, updatedBy: row.updated_by, updatedAt: row.updated_at.valueOf() } : { enabled: false, message: 'ProfitPilot is temporarily under maintenance.', version: 0, updatedBy: 'system', updatedAt: 0 } }
  public async saveMaintenance(next: MaintenanceState, expectedVersion: number): Promise<boolean> { const result = await this.executor.query('UPDATE platform_controls SET maintenance_enabled = $1, maintenance_message = $2, version = $3, updated_by = $4, updated_at = to_timestamp($5 / 1000.0) WHERE id = true AND version = $6', [next.enabled, next.message, next.version, next.updatedBy, next.updatedAt, expectedVersion]); return result.rowCount === 1 }
  public async getFlags(storeId: string): Promise<MerchantFlags> { const result = await this.executor.query<FlagRow>('SELECT store_id, ai_enabled, automation_enabled, suspended, version, updated_by, updated_at FROM merchant_controls WHERE store_id = $1 LIMIT 1', [storeId]); const row = result.rows[0]; return row ? { storeId: row.store_id, aiEnabled: row.ai_enabled, automationEnabled: row.automation_enabled, suspended: row.suspended, version: row.version, updatedBy: row.updated_by, updatedAt: row.updated_at.valueOf() } : { storeId, aiEnabled: true, automationEnabled: true, suspended: false, version: 0, updatedBy: 'system', updatedAt: 0 } }
  public async saveFlags(next: MerchantFlags, expectedVersion: number): Promise<boolean> { const result = await this.executor.query('INSERT INTO merchant_controls (store_id, ai_enabled, automation_enabled, suspended, version, updated_by, updated_at) VALUES ($1, $2, $3, $4, $5, $6, to_timestamp($7 / 1000.0)) ON CONFLICT (store_id) DO UPDATE SET ai_enabled = EXCLUDED.ai_enabled, automation_enabled = EXCLUDED.automation_enabled, suspended = EXCLUDED.suspended, version = EXCLUDED.version, updated_by = EXCLUDED.updated_by, updated_at = EXCLUDED.updated_at WHERE merchant_controls.version = $8 RETURNING store_id', [next.storeId, next.aiEnabled, next.automationEnabled, next.suspended, next.version, next.updatedBy, next.updatedAt, expectedVersion]); return result.rowCount === 1 }
  public async appendAudit(event: ControlAuditEvent): Promise<void> { await this.executor.query('INSERT INTO launch_control_audit (id, store_id, actor_id, action, before_state, after_state, created_at) VALUES ($1, $2, $3, $4, $5::jsonb, $6::jsonb, to_timestamp($7 / 1000.0))', [event.id, event.storeId, event.actorId, event.action, JSON.stringify(event.before), JSON.stringify(event.after), event.at]) }
  public async listAudit(storeId?: string): Promise<readonly ControlAuditEvent[]> { const result = storeId === undefined ? await this.executor.query<AuditRow>('SELECT id, store_id, actor_id, action, before_state, after_state, created_at FROM launch_control_audit ORDER BY created_at DESC') : await this.executor.query<AuditRow>('SELECT id, store_id, actor_id, action, before_state, after_state, created_at FROM launch_control_audit WHERE store_id = $1 ORDER BY created_at DESC', [storeId]); return result.rows.map(toAudit) }
}

function toAudit(row: AuditRow): ControlAuditEvent { return { id: row.id, storeId: row.store_id, actorId: row.actor_id, action: row.action, before: stateObject(row.before_state), after: stateObject(row.after_state), at: row.created_at.valueOf() } }
function stateObject(value: unknown): Readonly<Record<string, string | number | boolean | null>> { if (typeof value !== 'object' || value === null || Array.isArray(value)) return {}; const result: Record<string, string | number | boolean | null> = {}; for (const [key, item] of Object.entries(value)) if (item === null || typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean') result[key] = item; return result }
