import { randomUUID } from 'node:crypto'
import type { QueryResultRow, SqlExecutor } from '@profitpilot/db'
import { withTenantContext } from '@profitpilot/db'
import type { ActivatedWorkflow } from './workflows.js'
import type { ApprovalRecord, AutomationSummary, RunRepository, RunStatus, WorkflowRunRecord, WorkflowStepRecord } from './execution.js'
import { approvalPayloadHash } from './execution.js'

export class InMemoryRunRepository implements RunRepository {
  private readonly runs = new Map<string, WorkflowRunRecord>(); private readonly runContext = new Map<string, Readonly<Record<string, unknown>>>(); private readonly stepRecords = new Map<string, WorkflowStepRecord>(); private readonly approvalRecords = new Map<string, ApprovalRecord>()
  private key(storeId:string,id:string){return `${storeId}:${id}`}
  public async create(input:{workflow:ActivatedWorkflow;triggerType:string;triggerEventId?:string;context:Readonly<Record<string,unknown>>;testMode:boolean;maxAttempts?:number}):Promise<WorkflowRunRecord>{const now=new Date().toISOString();const record:WorkflowRunRecord={id:randomUUID(),workflowId:input.workflow.id,storeId:input.workflow.storeId,version:input.workflow.version,definitionHash:input.workflow.definitionHash,status:'QUEUED',currentNodeId:null,resumeAt:null,triggerType:input.triggerType,testMode:input.testMode,createdAt:now,startedAt:null,completedAt:null,errorMessage:null,attempt:0,maxAttempts:input.maxAttempts??3};this.runs.set(this.key(record.storeId,record.id),record);this.runContext.set(this.key(record.storeId,record.id),input.context);return record}
  public async get(storeId:string,runId:string){return this.runs.get(this.key(storeId,runId))??null}
  public async list(storeId:string,workflowId:string|null,limit=20,cursor='0'){const all=[...this.runs.values()].filter(r=>r.storeId===storeId&&(!workflowId||r.workflowId===workflowId)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const offset=Number(cursor)||0;return{items:all.slice(offset,offset+limit),nextCursor:offset+limit<all.length?String(offset+limit):null}}
  public async steps(storeId:string,runId:string){return [...this.stepRecords.values()].filter(s=>this.key(storeId,s.runId)===this.key(storeId,runId)).sort((a,b)=>a.sequence-b.sequence)}
  public async saveStep(storeId:string,step:WorkflowStepRecord){this.stepRecords.set(this.key(storeId,step.key),step)}
  public async transition(storeId:string,runId:string,status:RunStatus,fields:{nodeId?:string|null;resumeAt?:string|null;error?:string|null}={}){const current=await this.get(storeId,runId);if(!current)throw new Error('Run not found');const now=new Date().toISOString();const next={...current,status,currentNodeId:fields.nodeId===undefined?current.currentNodeId:fields.nodeId,resumeAt:fields.resumeAt===undefined?current.resumeAt:fields.resumeAt,errorMessage:fields.error===undefined?current.errorMessage:fields.error,startedAt:status==='RUNNING'?(current.startedAt??now):current.startedAt,completedAt:['COMPLETED','FAILED','CANCELLED'].includes(status)?now:current.completedAt};this.runs.set(this.key(storeId,runId),next);return next}
  public async context(storeId:string,runId:string){return this.runContext.get(this.key(storeId,runId))??{}}
  public async dueWaiting(){return [...this.runs.values()].filter(r=>r.status==='WAITING'&&r.resumeAt!==null&&Date.parse(r.resumeAt)<=Date.now())}
  public async createApproval(input:Omit<ApprovalRecord,'id'|'status'|'requestedAt'|'decidedAt'|'decidedBy'|'decisionReason'>&{payload:Readonly<Record<string,unknown>>;definitionHash:string;version:number}){const existing=[...this.approvalRecords.values()].find(a=>a.storeId===input.storeId&&a.runId===input.runId&&a.nodeId===input.nodeId);if(existing)return existing;const record:ApprovalRecord={id:randomUUID(),storeId:input.storeId,workflowId:input.workflowId,workflowName:input.workflowName,runId:input.runId,nodeId:input.nodeId,actionType:input.actionType,preview:input.preview,riskLevel:input.riskLevel,status:'PENDING',requestedAt:new Date().toISOString(),expiresAt:input.expiresAt,decidedAt:null,decidedBy:null,decisionReason:null};this.approvalRecords.set(this.key(record.storeId,record.id),record);return record}
  public async approvals(storeId:string,status?:ApprovalRecord['status']){return [...this.approvalRecords.values()].filter(a=>a.storeId===storeId&&(!status||a.status===status))}
  public async decideApproval(storeId:string,id:string,decision:'APPROVED'|'REJECTED',actor:string,reason?:string){const current=this.approvalRecords.get(this.key(storeId,id));if(!current||current.status!=='PENDING')return null;const next={...current,status:decision,decidedAt:new Date().toISOString(),decidedBy:actor,decisionReason:reason??null};this.approvalRecords.set(this.key(storeId,id),next);return next}
  public async countsToday(storeId:string,workflowId:string){const today=new Date().toISOString().slice(0,10);const records=[...this.runs.values()].filter(run=>run.storeId===storeId&&run.createdAt.startsWith(today));return{workflow:records.filter(run=>run.workflowId===workflowId).length,store:records.length}}
  public async summary(storeId:string):Promise<AutomationSummary>{const runs=[...this.runs.values()].filter(r=>r.storeId===storeId);const approvals=[...this.approvalRecords.values()].filter(a=>a.storeId===storeId&&a.status==='PENDING').length;const complete=runs.filter(r=>r.status==='COMPLETED').length;const failed=runs.filter(r=>r.status==='FAILED').length;return{workflows:{active:0,draft:0,paused:0,archived:0},runs:{today:runs.length,thisMonth:runs.length,previousMonth:0,completed:complete,failed,waiting:runs.filter(r=>r.status==='WAITING').length,successRate:complete+failed?complete/(complete+failed)*100:null},impact:{emailsSent:0,customersTagged:0,discountsCreated:0,notificationsSent:0},approvalsPending:approvals,recentActivity:[]}}
}

type RunRow=QueryResultRow&{id:string;workflow_id:string;store_id:string;version:number;definition_hash:string;status:RunStatus;current_node_id:string|null;resume_at:Date|null;trigger_type:string;test_mode:boolean;created_at:Date;started_at:Date|null;completed_at:Date|null;error_message:string|null;attempt:number;max_attempts:number;context:Readonly<Record<string,unknown>>}
type StepRow=QueryResultRow&{key:string;run_id:string;node_id:string;sequence:number;status:WorkflowStepRecord['status'];input:Readonly<Record<string,unknown>>;output:Readonly<Record<string,unknown>>;error_message:string|null;started_at:Date|null;completed_at:Date|null;duration_ms:number|null}
type ApprovalRow=QueryResultRow&{id:string;store_id:string;workflow_id:string;workflow_name:string;run_id:string;node_id:string;action_type:string;preview:string;risk_level:ApprovalRecord['riskLevel'];status:ApprovalRecord['status'];requested_at:Date;expires_at:Date;decided_at:Date|null;decided_by:string|null;decision_reason:string|null}
export class PostgresRunRepository implements RunRepository {
  public constructor(private readonly db:SqlExecutor){}
  public create(input:{workflow:ActivatedWorkflow;triggerType:string;triggerEventId?:string;context:Readonly<Record<string,unknown>>;testMode:boolean;maxAttempts?:number}):Promise<WorkflowRunRecord>{return withTenantContext(this.db,input.workflow.storeId,async c=>{const r=await c.query<RunRow>(`INSERT INTO workflow_runs(id,workflow_id,store_id,status,version,definition_hash,trigger_type,trigger_event_id,context,test_mode,max_attempts) VALUES($1,$2,$3,'QUEUED',$4,$5,$6,$7,$8::jsonb,$9,$10) ON CONFLICT(store_id,trigger_event_id,workflow_id) WHERE trigger_event_id IS NOT NULL DO UPDATE SET trigger_event_id=EXCLUDED.trigger_event_id RETURNING *`,[randomUUID(),input.workflow.id,input.workflow.storeId,input.workflow.version,input.workflow.definitionHash,input.triggerType,input.triggerEventId??null,JSON.stringify(input.context),input.testMode,input.maxAttempts??3]);return mapRun(r.rows[0]!)})}
  public get(storeId:string,runId:string):Promise<WorkflowRunRecord|null>{return withTenantContext(this.db,storeId,async c=>{const r=await c.query<RunRow>('SELECT * FROM workflow_runs WHERE store_id=$1 AND id=$2',[storeId,runId]);return r.rows[0]?mapRun(r.rows[0]):null})}
  public list(storeId:string,workflowId:string|null,limit=20,cursor='0'){return withTenantContext(this.db,storeId,async c=>{const offset=Number(cursor)||0;const r=await c.query<RunRow>('SELECT * FROM workflow_runs WHERE store_id=$1 AND ($2::uuid IS NULL OR workflow_id=$2) ORDER BY created_at DESC LIMIT $3 OFFSET $4',[storeId,workflowId,Math.min(50,limit),offset]);return{items:r.rows.map(mapRun),nextCursor:r.rows.length===Math.min(50,limit)?String(offset+Math.min(50,limit)):null}})}
  public steps(storeId:string,runId:string){return withTenantContext(this.db,storeId,async c=>(await c.query<StepRow>('SELECT * FROM workflow_steps WHERE store_id=$1 AND run_id=$2 ORDER BY sequence',[storeId,runId])).rows.map(mapStep))}
  public saveStep(storeId:string,s:WorkflowStepRecord):Promise<void>{return withTenantContext(this.db,storeId,async c=>{await c.query(`INSERT INTO workflow_steps(key,run_id,store_id,node_id,sequence,status,input,output,error_message,started_at,completed_at,duration_ms) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9,$10,$11,$12) ON CONFLICT(key) DO UPDATE SET status=EXCLUDED.status,input=EXCLUDED.input,output=EXCLUDED.output,error_message=EXCLUDED.error_message,started_at=COALESCE(workflow_steps.started_at,EXCLUDED.started_at),completed_at=EXCLUDED.completed_at,duration_ms=EXCLUDED.duration_ms,updated_at=now()`,[s.key,s.runId,storeId,s.nodeId,s.sequence,s.status,JSON.stringify(s.input),JSON.stringify(s.output),s.errorMessage,s.startedAt,s.completedAt,s.durationMs])})}
  public transition(storeId:string,runId:string,status:RunStatus,f:{nodeId?:string|null;resumeAt?:string|null;error?:string|null}={}):Promise<WorkflowRunRecord>{return withTenantContext(this.db,storeId,async c=>{const r=await c.query<RunRow>(`UPDATE workflow_runs SET status=$3,current_node_id=CASE WHEN $4::boolean THEN $5 ELSE current_node_id END,resume_at=CASE WHEN $6::boolean THEN $7::timestamptz ELSE resume_at END,error_message=CASE WHEN $8::boolean THEN $9 ELSE error_message END,started_at=CASE WHEN $3='RUNNING' THEN COALESCE(started_at,now()) ELSE started_at END,completed_at=CASE WHEN $3 IN('COMPLETED','FAILED','CANCELLED') THEN now() ELSE completed_at END,updated_at=now() WHERE store_id=$1 AND id=$2 RETURNING *`,[storeId,runId,status,f.nodeId!==undefined,f.nodeId??null,f.resumeAt!==undefined,f.resumeAt??null,f.error!==undefined,f.error??null]);if(!r.rows[0])throw new Error('Run not found');if(status==='COMPLETED'||status==='FAILED')await c.query(`UPDATE workflows SET last_run_at=now(),success_count=success_count+CASE WHEN $3='COMPLETED' THEN 1 ELSE 0 END,failure_count=failure_count+CASE WHEN $3='FAILED' THEN 1 ELSE 0 END WHERE store_id=$1 AND id=(SELECT workflow_id FROM workflow_runs WHERE id=$2)`,[storeId,runId,status]);return mapRun(r.rows[0])})}
  public context(storeId:string,runId:string){return withTenantContext(this.db,storeId,async c=>(await c.query<RunRow>('SELECT context FROM workflow_runs WHERE store_id=$1 AND id=$2',[storeId,runId])).rows[0]?.context??{})}
  public async dueWaiting(limit=100):Promise<readonly WorkflowRunRecord[]>{const stores=await this.db.query<QueryResultRow&{id:string}>('SELECT id FROM stores ORDER BY id');const due:WorkflowRunRecord[]=[];for(const store of stores.rows){if(due.length>=limit)break;const rows=await withTenantContext(this.db,store.id,async client=>client.query<RunRow>(`SELECT * FROM workflow_runs WHERE store_id=$1 AND status='WAITING' AND resume_at<=now() ORDER BY resume_at LIMIT $2`,[store.id,limit-due.length]));due.push(...rows.rows.map(mapRun))}return due}
  public createApproval(input:Omit<ApprovalRecord,'id'|'status'|'requestedAt'|'decidedAt'|'decidedBy'|'decisionReason'>&{payload:Readonly<Record<string,unknown>>;definitionHash:string;version:number}){return withTenantContext(this.db,input.storeId,async c=>{const hash=approvalPayloadHash(input.payload);const r=await c.query<ApprovalRow>(`INSERT INTO workflow_approvals(store_id,workflow_id,workflow_name,run_id,node_id,version,definition_hash,action_type,action_payload,payload_hash,preview,risk_level,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$12,$13) ON CONFLICT(store_id,run_id,node_id,payload_hash) DO UPDATE SET payload_hash=EXCLUDED.payload_hash RETURNING *`,[input.storeId,input.workflowId,input.workflowName,input.runId,input.nodeId,input.version,input.definitionHash,input.actionType,JSON.stringify(input.payload),hash,input.preview,input.riskLevel,input.expiresAt]);await c.query(`INSERT INTO merchant_notifications(store_id,kind,title,message,workflow_id,run_id) VALUES($1,'APPROVAL_REQUIRED','Workflow approval required',$2,$3,$4)`,[input.storeId,input.preview,input.workflowId,input.runId]);return mapApproval(r.rows[0]!)})}
  public approvals(storeId:string,status?:ApprovalRecord['status']){return withTenantContext(this.db,storeId,async c=>{await c.query(`UPDATE workflow_approvals SET status='EXPIRED',decided_at=now(),decision_reason='Approval expired' WHERE store_id=$1 AND status='PENDING' AND expires_at<=now()`,[storeId]);return(await c.query<ApprovalRow>('SELECT * FROM workflow_approvals WHERE store_id=$1 AND ($2::text IS NULL OR status=$2) ORDER BY requested_at DESC',[storeId,status??null])).rows.map(mapApproval)})}
  public decideApproval(storeId:string,id:string,decision:'APPROVED'|'REJECTED',actor:string,reason?:string){return withTenantContext(this.db,storeId,async c=>{const r=await c.query<ApprovalRow>(`UPDATE workflow_approvals SET status=$3,decided_at=now(),decided_by=$4,decision_reason=$5 WHERE store_id=$1 AND id=$2 AND status='PENDING' AND expires_at>now() RETURNING *`,[storeId,id,decision,actor,reason??null]);return r.rows[0]?mapApproval(r.rows[0]):null})}
  public countsToday(storeId:string,workflowId:string){return withTenantContext(this.db,storeId,async c=>{const result=await c.query<QueryResultRow&{workflow:string;store:string}>(`SELECT count(*) FILTER(WHERE workflow_id=$2) workflow,count(*) store FROM workflow_runs WHERE store_id=$1 AND created_at>=CURRENT_DATE`,[storeId,workflowId]);return{workflow:Number(result.rows[0]?.workflow??0),store:Number(result.rows[0]?.store??0)}})}
  public summary(storeId:string):Promise<AutomationSummary>{return withTenantContext(this.db,storeId,async c=>{const w=await c.query<QueryResultRow&{status:string;count:string}>('SELECT status,count(*) FROM workflows WHERE store_id=$1 GROUP BY status',[storeId]);const r=await c.query<QueryResultRow&{today:string;month:string;previous:string;completed:string;failed:string;waiting:string}>(`SELECT count(*) FILTER(WHERE created_at>=CURRENT_DATE) today,count(*) FILTER(WHERE created_at>=date_trunc('month',now())) month,count(*) FILTER(WHERE created_at>=date_trunc('month',now())-interval '1 month' AND created_at<date_trunc('month',now())) previous,count(*) FILTER(WHERE status='COMPLETED') completed,count(*) FILTER(WHERE status='FAILED') failed,count(*) FILTER(WHERE status='WAITING') waiting FROM workflow_runs WHERE store_id=$1`,[storeId]);const i=await c.query<QueryResultRow&{emails:string;tags:string;discounts:string;notifications:string}>(`SELECT count(*) FILTER(WHERE output->>'action'='email') emails,count(*) FILTER(WHERE output->>'action'='tag_customer') tags,count(*) FILTER(WHERE output->>'action'='create_discount') discounts,count(*) FILTER(WHERE output->>'action'='internal_notification') notifications FROM workflow_steps WHERE store_id=$1 AND status='COMPLETED'`,[storeId]);const a=await c.query<QueryResultRow&{count:string}>(`SELECT count(*) FROM workflow_approvals WHERE store_id=$1 AND status='PENDING' AND expires_at>now()`,[storeId]);const activity=await c.query<QueryResultRow&{id:string;workflow_id:string;name:string;status:RunStatus;created_at:Date}>(`SELECT r.id,r.workflow_id,w.name,r.status,COALESCE(r.completed_at,r.started_at,r.created_at) created_at FROM workflow_runs r JOIN workflows w ON w.id=r.workflow_id AND w.store_id=r.store_id WHERE r.store_id=$1 ORDER BY created_at DESC LIMIT 20`,[storeId]);const status=Object.fromEntries(w.rows.map(x=>[x.status.toLowerCase(),Number(x.count)]));const rr=r.rows[0]!;const completed=Number(rr.completed),failed=Number(rr.failed);const ii=i.rows[0]!;return{workflows:{active:status.active??0,draft:status.draft??0,paused:status.paused??0,archived:status.archived??0},runs:{today:Number(rr.today),thisMonth:Number(rr.month),previousMonth:Number(rr.previous),completed,failed,waiting:Number(rr.waiting),successRate:completed+failed?completed/(completed+failed)*100:null},impact:{emailsSent:Number(ii.emails),customersTagged:Number(ii.tags),discountsCreated:Number(ii.discounts),notificationsSent:Number(ii.notifications)},approvalsPending:Number(a.rows[0]?.count??0),recentActivity:activity.rows.map(x=>({runId:x.id,workflowId:x.workflow_id,workflowName:x.name,status:x.status,at:x.created_at.toISOString(),description:`Workflow run ${x.status.toLowerCase().replace('_',' ')}`}))}})}
}
function mapRun(r:RunRow):WorkflowRunRecord{return{id:r.id,workflowId:r.workflow_id,storeId:r.store_id,version:r.version,definitionHash:r.definition_hash,status:r.status,currentNodeId:r.current_node_id,resumeAt:r.resume_at?.toISOString()??null,triggerType:r.trigger_type,testMode:r.test_mode,createdAt:r.created_at.toISOString(),startedAt:r.started_at?.toISOString()??null,completedAt:r.completed_at?.toISOString()??null,errorMessage:r.error_message,attempt:r.attempt,maxAttempts:r.max_attempts}}
function mapStep(s:StepRow):WorkflowStepRecord{return{key:s.key,runId:s.run_id,nodeId:s.node_id,sequence:s.sequence,status:s.status,input:s.input,output:s.output,errorMessage:s.error_message,startedAt:s.started_at?.toISOString()??null,completedAt:s.completed_at?.toISOString()??null,durationMs:s.duration_ms}}
function mapApproval(a:ApprovalRow):ApprovalRecord{return{id:a.id,storeId:a.store_id,workflowId:a.workflow_id,workflowName:a.workflow_name,runId:a.run_id,nodeId:a.node_id,actionType:a.action_type,preview:a.preview,riskLevel:a.risk_level,status:a.status,requestedAt:a.requested_at.toISOString(),expiresAt:a.expires_at.toISOString(),decidedAt:a.decided_at?.toISOString()??null,decidedBy:a.decided_by,decisionReason:a.decision_reason}}
