import type { SqlExecutor, QueryResultRow } from '@profitpilot/db'
import { withTenantContext } from '@profitpilot/db'
import type { CampaignTemplate } from './campaigns.js'
import type { MerchantEmailConfig } from './email.js'
import type { ActivatedWorkflow, WorkflowCategory, WorkflowDefinition, WorkflowStatus } from './workflows.js'
import { triggerSummary } from './workflows.js'

export type WorkflowRecord = Readonly<WorkflowDefinition & {
  status: WorkflowStatus
  definitionHash: string | null
  activatedAt: string | null
  createdAt: string
  updatedAt: string
  createdBy: string
  updatedBy: string
  lastRunAt: string | null
  successCount: number
  failureCount: number
  enabled: boolean
  triggerSummary: string
  nodeCount: number
  nextRunAt: string | null
}>
export type WorkflowListQuery = Readonly<{ status?: WorkflowStatus; category?: WorkflowCategory; search?: string; sort?: 'name' | 'created' | 'lastRun' | 'successRate'; direction?: 'asc' | 'desc'; cursor?: string; limit?: number }>
export type WorkflowPage = Readonly<{ items: readonly WorkflowRecord[]; nextCursor: string | null; total: number }>
export type WorkflowPatch = Readonly<{ name?: string; description?: string | null; category?: WorkflowCategory; tags?: readonly string[]; nodes?: WorkflowDefinition['nodes']; enabled?: boolean; timezone?: string; overlapPolicy?: WorkflowDefinition['overlapPolicy'] }>
export interface WorkflowRepository {
  put(definition: WorkflowDefinition, actor?: string): Promise<WorkflowRecord>
  get(storeId: string, id: string): Promise<WorkflowRecord | null>
  activate(storeId: string, workflow: ActivatedWorkflow, actor?: string): Promise<WorkflowRecord>
  list(storeId: string, query?: WorkflowListQuery): Promise<WorkflowPage>
  patch(storeId: string, id: string, patch: WorkflowPatch, actor: string): Promise<WorkflowRecord | null>
  setStatus(storeId: string, id: string, status: WorkflowStatus, actor: string): Promise<WorkflowRecord | null>
  clone(storeId: string, id: string, newId: string, name: string, actor: string): Promise<WorkflowRecord | null>
  versions(storeId: string, id: string): Promise<readonly Readonly<{ version: number; definitionHash: string; createdAt: string; publishedAt: string | null }>[]>
  version(storeId: string, id: string, version: number): Promise<WorkflowDefinition | null>
  count(storeId: string): Promise<number>
}
export interface TemplateRepository { put(template: CampaignTemplate): Promise<void>; get(storeId: string, id: string): Promise<CampaignTemplate | null>; list(storeId?: string): Promise<readonly CampaignTemplate[]> }
export interface MerchantEmailConfigRepository { put(config: MerchantEmailConfig): Promise<void>; get(storeId: string): Promise<MerchantEmailConfig | null> }

export class InMemoryWorkflowRepository implements WorkflowRepository {
  private readonly records = new Map<string, WorkflowRecord>()
  private readonly history = new Map<string, Array<{ version: number; definitionHash: string; createdAt: string; publishedAt: string | null }>>()
  private readonly versionDefinitions = new Map<string, WorkflowDefinition>()
  private key(storeId: string, id: string) { return `${storeId}:${id}` }
  public async put(definition: WorkflowDefinition, actor = 'merchant'): Promise<WorkflowRecord> { const now = new Date().toISOString(); const existing = this.records.get(this.key(definition.storeId, definition.id)); const record: WorkflowRecord = { ...definition, status: existing?.status ?? 'DRAFT', definitionHash: existing?.definitionHash ?? null, activatedAt: existing?.activatedAt ?? null, createdAt: existing?.createdAt ?? now, updatedAt: now, createdBy: existing?.createdBy ?? actor, updatedBy: actor, lastRunAt: existing?.lastRunAt ?? null, successCount: existing?.successCount ?? 0, failureCount: existing?.failureCount ?? 0, enabled: existing?.enabled ?? true, triggerSummary: triggerSummary(definition), nodeCount: definition.nodes.length, nextRunAt: existing?.nextRunAt ?? null }; this.records.set(this.key(definition.storeId, definition.id), record); return record }
  public async get(storeId: string, id: string): Promise<WorkflowRecord | null> { return this.records.get(this.key(storeId, id)) ?? null }
  public async activate(storeId: string, workflow: ActivatedWorkflow, actor = 'merchant'): Promise<WorkflowRecord> { const record = await this.put(workflow, actor); const active: WorkflowRecord = { ...record, status: 'ACTIVE', definitionHash: workflow.definitionHash, activatedAt: workflow.activatedAt, updatedAt: workflow.activatedAt }; this.records.set(this.key(storeId, workflow.id), active); const versions = this.history.get(this.key(storeId, workflow.id)) ?? []; if (!versions.some((item) => item.definitionHash === workflow.definitionHash)) versions.push({ version: workflow.version, definitionHash: workflow.definitionHash, createdAt: workflow.activatedAt, publishedAt: workflow.activatedAt }); this.history.set(this.key(storeId, workflow.id), versions); this.versionDefinitions.set(`${this.key(storeId, workflow.id)}:${workflow.version}`, workflow); return active }
  public async list(storeId: string, query: WorkflowListQuery = {}): Promise<WorkflowPage> { let items = [...this.records.values()].filter((item) => item.storeId === storeId); if (query.status) items = items.filter((item) => item.status === query.status); if (query.category) items = items.filter((item) => item.category === query.category); if (query.search) { const term = query.search.toLowerCase(); items = items.filter((item) => `${item.name} ${item.description ?? ''}`.toLowerCase().includes(term)) } items.sort((a, b) => (query.direction === 'asc' ? 1 : -1) * a.updatedAt.localeCompare(b.updatedAt)); const total = items.length; const offset = query.cursor ? Number(query.cursor) || 0 : 0; const limit = Math.min(50, Math.max(1, query.limit ?? 20)); return { items: items.slice(offset, offset + limit), nextCursor: offset + limit < total ? String(offset + limit) : null, total } }
  public async patch(storeId: string, id: string, patch: WorkflowPatch, actor: string): Promise<WorkflowRecord | null> { const current = await this.get(storeId, id); if (!current) return null; const nextDefinition: WorkflowDefinition = { ...current, ...patch, version: patch.nodes ? current.version + 1 : current.version }; const record = await this.put(nextDefinition, actor); const next = { ...record, status: patch.nodes && current.status === 'ACTIVE' ? 'DRAFT' as const : current.status, definitionHash: patch.nodes ? null : current.definitionHash }; this.records.set(this.key(storeId, id), next); return next }
  public async setStatus(storeId: string, id: string, status: WorkflowStatus, actor: string): Promise<WorkflowRecord | null> { const current = await this.get(storeId, id); if (!current) return null; const next = { ...current, status, enabled: status === 'ACTIVE' ? true : status === 'PAUSED' ? false : current.enabled, updatedBy: actor, updatedAt: new Date().toISOString() }; this.records.set(this.key(storeId, id), next); return next }
  public async clone(storeId: string, id: string, newId: string, name: string, actor: string): Promise<WorkflowRecord | null> { const current = await this.get(storeId, id); return current ? this.put({ ...current, id: newId, name, version: 1 }, actor) : null }
  public async versions(storeId: string, id: string) { return this.history.get(this.key(storeId, id)) ?? [] }
  public async version(storeId: string, id: string, version: number) { return this.versionDefinitions.get(`${this.key(storeId, id)}:${version}`) ?? null }
  public async count(storeId: string): Promise<number> { return [...this.records.values()].filter((record) => record.storeId === storeId && record.status !== 'ARCHIVED').length }
  public activeFor(id: string): ActivatedWorkflow | null { const found = [...this.records.values()].find((record) => record.id === id && record.status === 'ACTIVE'); return found?.definitionHash && found.activatedAt ? { ...found, definitionHash: found.definitionHash, activatedAt: found.activatedAt } : null }
}

export class InMemoryTemplateRepository implements TemplateRepository { private readonly templates = new Map<string, CampaignTemplate>(); public async put(template: CampaignTemplate): Promise<void> { this.templates.set(`${template.storeId}:${template.id}`, template) }; public async get(storeId: string, id: string): Promise<CampaignTemplate | null> { return this.templates.get(`${storeId}:${id}`) ?? null }; public async list(storeId?: string): Promise<readonly CampaignTemplate[]> { return [...this.templates.values()].filter((template) => storeId === undefined || template.storeId === storeId) } }
export class InMemoryMerchantEmailConfigRepository implements MerchantEmailConfigRepository { private readonly configs = new Map<string, MerchantEmailConfig>(); public async put(config: MerchantEmailConfig): Promise<void> { this.configs.set(config.shopId, { ...config }) }; public async get(storeId: string): Promise<MerchantEmailConfig | null> { return this.configs.get(storeId) ?? null } }

type WorkflowRow = QueryResultRow & { id: string; store_id: string; version: number; definition: WorkflowDefinition; definition_hash: string | null; status: WorkflowStatus; name: string; description: string | null; category: WorkflowCategory; tags: readonly string[]; created_by: string; updated_by: string; created_at: Date; updated_at: Date; activated_at: Date | null; last_run_at: Date | null; success_count: number; failure_count: number; enabled: boolean; trigger_summary: string; node_count: number; next_run_at: Date | null }
type TemplateRow = QueryResultRow & { id: string; store_id: string; name: string; kind: 'EMAIL' | 'SMS'; subject: string; body: string; variables: readonly string[] }
const SELECT_WORKFLOW = 'SELECT id, store_id, version, definition, definition_hash, status, name, description, category, tags, created_by, updated_by, created_at, updated_at, activated_at, last_run_at, success_count, failure_count, enabled, trigger_summary, node_count, next_run_at FROM workflows'

export class PostgresWorkflowRepository implements WorkflowRepository {
  public constructor(private readonly executor: SqlExecutor) {}
  public put(definition: WorkflowDefinition, actor = 'merchant'): Promise<WorkflowRecord> { return withTenantContext(this.executor, definition.storeId, async (client) => { const result = await client.query<WorkflowRow>(`INSERT INTO workflows (id, store_id, version, definition_hash, definition, status, name, description, category, tags, created_by, updated_by, trigger_summary, node_count) VALUES ($1,$2,$3,'',$4::jsonb,'DRAFT',$5,$6,$7,$8,$9,$9,$10,$11) ON CONFLICT (id) DO UPDATE SET version=EXCLUDED.version, definition=EXCLUDED.definition, name=EXCLUDED.name, description=EXCLUDED.description, category=EXCLUDED.category, tags=EXCLUDED.tags, updated_by=EXCLUDED.updated_by, updated_at=now(), trigger_summary=EXCLUDED.trigger_summary, node_count=EXCLUDED.node_count WHERE workflows.store_id=EXCLUDED.store_id RETURNING *`, [definition.id, definition.storeId, definition.version, JSON.stringify(definition), definition.name, definition.description, definition.category, definition.tags, actor, triggerSummary(definition), definition.nodes.length]); return toWorkflow(requiredRow(result.rows[0])) }) }
  public get(storeId: string, id: string): Promise<WorkflowRecord | null> { return withTenantContext(this.executor, storeId, async (client) => { const result = await client.query<WorkflowRow>(`${SELECT_WORKFLOW} WHERE store_id=$1 AND id=$2 LIMIT 1`, [storeId, id]); return result.rows[0] ? toWorkflow(result.rows[0]) : null }) }
  public activate(storeId: string, workflow: ActivatedWorkflow, actor = 'merchant'): Promise<WorkflowRecord> { return withTenantContext(this.executor, storeId, async (client) => { await client.query(`INSERT INTO workflow_versions (workflow_id,store_id,version,definition_hash,definition,created_by,published_at) VALUES ($1,$2,$3,$4,$5::jsonb,$6,$7) ON CONFLICT (store_id,workflow_id,definition_hash) DO NOTHING`, [workflow.id, storeId, workflow.version, workflow.definitionHash, JSON.stringify(workflow), actor, workflow.activatedAt]); const result = await client.query<WorkflowRow>(`UPDATE workflows SET status='ACTIVE', enabled=true, definition_hash=$3, activated_at=$4, updated_at=now(), updated_by=$5 WHERE store_id=$1 AND id=$2 RETURNING *`, [storeId, workflow.id, workflow.definitionHash, workflow.activatedAt, actor]); return toWorkflow(requiredRow(result.rows[0])) }) }
  public list(storeId: string, query: WorkflowListQuery = {}): Promise<WorkflowPage> { return withTenantContext(this.executor, storeId, async (client) => { const conditions = ['store_id=$1']; const values: unknown[] = [storeId]; if (query.status) { values.push(query.status); conditions.push(`status=$${values.length}`) } if (query.category) { values.push(query.category); conditions.push(`category=$${values.length}`) } if (query.search) { values.push(`%${query.search}%`); conditions.push(`(name ILIKE $${values.length} OR description ILIKE $${values.length})`) } const count = await client.query<QueryResultRow & { total: string }>(`SELECT count(*) AS total FROM workflows WHERE ${conditions.join(' AND ')}`, values); const limit = Math.min(50, Math.max(1, query.limit ?? 20)); const offset = query.cursor ? Number(query.cursor) || 0 : 0; values.push(limit, offset); const sort = query.sort === 'name' ? 'name' : query.sort === 'created' ? 'created_at' : query.sort === 'lastRun' ? 'last_run_at' : query.sort === 'successRate' ? '(success_count::float / NULLIF(success_count + failure_count,0))' : 'updated_at'; const direction = query.direction === 'asc' ? 'ASC' : 'DESC'; const rows = await client.query<WorkflowRow>(`${SELECT_WORKFLOW} WHERE ${conditions.join(' AND ')} ORDER BY ${sort} ${direction} NULLS LAST, id ASC LIMIT $${values.length - 1} OFFSET $${values.length}`, values); const total = Number(count.rows[0]?.total ?? 0); return { items: rows.rows.map(toWorkflow), nextCursor: offset + limit < total ? String(offset + limit) : null, total } }) }
  public patch(storeId: string, id: string, patch: WorkflowPatch, actor: string): Promise<WorkflowRecord | null> { return withTenantContext(this.executor, storeId, async (client) => { const currentResult = await client.query<WorkflowRow>(`${SELECT_WORKFLOW} WHERE store_id=$1 AND id=$2`, [storeId, id]); const current = currentResult.rows[0] ? toWorkflow(currentResult.rows[0]) : null; if (!current) return null; const definition: WorkflowDefinition = { ...current, name: patch.name ?? current.name, description: patch.description === undefined ? current.description : patch.description, category: patch.category ?? current.category, tags: patch.tags ?? current.tags, nodes: patch.nodes ?? current.nodes, timezone: patch.timezone ?? current.timezone, overlapPolicy: patch.overlapPolicy ?? current.overlapPolicy, version: patch.nodes ? current.version + 1 : current.version }; const result = await client.query<WorkflowRow>(`UPDATE workflows SET name=$3,description=$4,category=$5,tags=$6,definition=$7::jsonb,version=$8,enabled=$9,updated_by=$10,updated_at=now(),trigger_summary=$11,node_count=$12,status=CASE WHEN $13 THEN 'DRAFT' ELSE status END,definition_hash=CASE WHEN $13 THEN '' ELSE definition_hash END WHERE store_id=$1 AND id=$2 RETURNING *`, [storeId,id,definition.name,definition.description,definition.category,definition.tags,JSON.stringify(definition),definition.version,patch.enabled ?? current.enabled,actor,triggerSummary(definition),definition.nodes.length,Boolean(patch.nodes)]); return result.rows[0] ? toWorkflow(result.rows[0]) : null }) }
  public setStatus(storeId: string, id: string, status: WorkflowStatus, actor: string): Promise<WorkflowRecord | null> { return withTenantContext(this.executor, storeId, async (client) => { const result = await client.query<WorkflowRow>(`UPDATE workflows SET status=$3,enabled=($3='ACTIVE'),updated_by=$4,updated_at=now(),archived_at=CASE WHEN $3='ARCHIVED' THEN now() ELSE archived_at END WHERE store_id=$1 AND id=$2 RETURNING *`, [storeId,id,status,actor]); return result.rows[0] ? toWorkflow(result.rows[0]) : null }) }
  public async clone(storeId: string, id: string, newId: string, name: string, actor: string): Promise<WorkflowRecord | null> { const current = await this.get(storeId,id); return current ? this.put({ ...current,id:newId,name,version:1 },actor) : null }
  public versions(storeId: string, id: string) { return withTenantContext(this.executor, storeId, async (client) => { const result = await client.query<QueryResultRow & { version:number; definition_hash:string; created_at:Date; published_at:Date|null }>('SELECT version,definition_hash,created_at,published_at FROM workflow_versions WHERE store_id=$1 AND workflow_id=$2 ORDER BY version DESC',[storeId,id]); return result.rows.map((row)=>({version:row.version,definitionHash:row.definition_hash,createdAt:row.created_at.toISOString(),publishedAt:row.published_at?.toISOString() ?? null})) }) }
  public version(storeId: string, id: string, version: number): Promise<WorkflowDefinition | null> { return withTenantContext(this.executor, storeId, async (client) => { const result = await client.query<QueryResultRow & { definition: WorkflowDefinition }>('SELECT definition FROM workflow_versions WHERE store_id=$1 AND workflow_id=$2 AND version=$3 LIMIT 1', [storeId,id,version]); return result.rows[0]?.definition ?? null }) }
  public count(storeId: string): Promise<number> { return withTenantContext(this.executor, storeId, async (client) => Number((await client.query<QueryResultRow & { total:string }>(`SELECT count(*) AS total FROM workflows WHERE store_id=$1 AND status<>'ARCHIVED'`,[storeId])).rows[0]?.total ?? 0)) }
}

export class PostgresTemplateRepository implements TemplateRepository { public constructor(private readonly executor: SqlExecutor) {}; public put(template: CampaignTemplate): Promise<void> { return withTenantContext(this.executor, template.storeId, async (client) => { await client.query(`INSERT INTO campaign_templates (id,store_id,name,kind,subject,body,variables) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,subject=EXCLUDED.subject,body=EXCLUDED.body,variables=EXCLUDED.variables WHERE campaign_templates.store_id=EXCLUDED.store_id`,[template.id,template.storeId,template.name,template.kind,template.subject,template.body,JSON.stringify(template.variables)]) }) }; public get(storeId:string,id:string):Promise<CampaignTemplate|null>{return withTenantContext(this.executor,storeId,async(client)=>{const result=await client.query<TemplateRow>('SELECT id,store_id,name,kind,subject,body,variables FROM campaign_templates WHERE store_id=$1 AND id=$2 LIMIT 1',[storeId,id]);return result.rows[0]?toTemplate(result.rows[0]):null})}; public list(storeId?:string):Promise<readonly CampaignTemplate[]>{if(!storeId)return Promise.resolve([]);return withTenantContext(this.executor,storeId,async(client)=>(await client.query<TemplateRow>('SELECT id,store_id,name,kind,subject,body,variables FROM campaign_templates WHERE store_id=$1 ORDER BY created_at DESC',[storeId])).rows.map(toTemplate))} }
export class PostgresMerchantEmailConfigRepository implements MerchantEmailConfigRepository { public constructor(private readonly executor:SqlExecutor){}; public put(config:MerchantEmailConfig):Promise<void>{return withTenantContext(this.executor,config.shopId,async(client)=>{await client.query(`INSERT INTO merchant_email_configs (store_id,merchant_email,from_name,verified,verification_sent_at,verified_at) VALUES ($1,$2,$3,$4,CASE WHEN $5::bigint IS NULL THEN NULL ELSE to_timestamp($5/1000.0) END,CASE WHEN $6::bigint IS NULL THEN NULL ELSE to_timestamp($6/1000.0) END) ON CONFLICT (store_id) DO UPDATE SET merchant_email=EXCLUDED.merchant_email,from_name=EXCLUDED.from_name,verified=EXCLUDED.verified,verification_sent_at=EXCLUDED.verification_sent_at,verified_at=EXCLUDED.verified_at`,[config.shopId,config.merchantEmail,config.fromName,config.verified,config.verificationSentAt,config.verifiedAt])})}; public get(storeId:string):Promise<MerchantEmailConfig|null>{return withTenantContext(this.executor,storeId,async(client)=>{const result=await client.query<QueryResultRow & {store_id:string;merchant_email:string;from_name:string;verified:boolean;verification_sent_at:Date|null;verified_at:Date|null}>('SELECT store_id,merchant_email,from_name,verified,verification_sent_at,verified_at FROM merchant_email_configs WHERE store_id=$1 LIMIT 1',[storeId]);const row=result.rows[0];return row?{shopId:row.store_id,merchantEmail:row.merchant_email,fromName:row.from_name,verified:row.verified,verificationSentAt:row.verification_sent_at?.valueOf()??null,verifiedAt:row.verified_at?.valueOf()??null}:null})} }

function requiredRow(row: WorkflowRow | undefined): WorkflowRow { if (!row) throw new Error('Workflow persistence did not return a row'); return row }
function toWorkflow(row:WorkflowRow):WorkflowRecord { return { ...row.definition,id:row.id,storeId:row.store_id as WorkflowRecord['storeId'],name:row.name,description:row.description,category:row.category,tags:row.tags,version:row.version,status:row.status,definitionHash:row.definition_hash || null,activatedAt:row.activated_at?.toISOString()??null,createdAt:row.created_at.toISOString(),updatedAt:row.updated_at.toISOString(),createdBy:row.created_by,updatedBy:row.updated_by,lastRunAt:row.last_run_at?.toISOString()??null,successCount:row.success_count,failureCount:row.failure_count,enabled:row.enabled,triggerSummary:row.trigger_summary,nodeCount:row.node_count,nextRunAt:row.next_run_at?.toISOString()??null} }
function toTemplate(row:TemplateRow):CampaignTemplate{return{id:row.id,storeId:row.store_id as WorkflowRecord['storeId'],name:row.name,kind:row.kind,subject:row.subject,body:row.body,variables:row.variables as CampaignTemplate['variables']}}
