import type { PlanTier, StoreId } from '@profitpilot/types'
import type { WorkflowCategory, WorkflowDefinition, WorkflowNode } from './workflows.js'

export type WorkflowTemplate = Readonly<{ id: string; name: string; description: string; category: WorkflowCategory; impact: string; complexity: 'Simple' | 'Medium' | 'Advanced'; minimumPlan: PlanTier; nodes: readonly WorkflowNode[] }>
const trigger = (event: string): WorkflowNode => event === 'manual' ? { id: 'trigger', type: 'trigger', config: { trigger: 'manual' }, next: ['action'] } : event.startsWith('cron:') ? { id: 'trigger', type: 'trigger', config: { trigger: 'cron', cron: event.slice(5) }, next: ['condition'] } : { id: 'trigger', type: 'trigger', config: { trigger: 'shopify_webhook', topic: event }, next: event.includes('customers/create') ? ['wait'] : ['condition'] }
const wait = (id: string, delayMs: number, next: string): WorkflowNode => ({ id, type: 'wait', config: { delayMs }, next: [next] })
const condition = (field: string, operator: string, value: string | number | boolean, yes = 'action', no = 'notify'): WorkflowNode => ({ id: 'condition', type: 'condition', config: { field, operator, value }, next: [yes, no] })
const action = (kind: string, config: Readonly<Record<string, string | number | boolean | null>> = {}, id = 'action'): WorkflowNode => ({ id, type: 'action', config: { action: kind, ...config }, next: [] })
const notify = (): WorkflowNode => action('internal_notification', { message: 'Workflow condition was not met.' }, 'notify')

export const WORKFLOW_TEMPLATES: readonly WorkflowTemplate[] = [
  { id: 'welcome-customer', name: 'Welcome New Customer', description: 'Welcome a new customer after a short, respectful delay.', category: 'Customer', impact: 'Supports a stronger first-purchase relationship.', complexity: 'Simple', minimumPlan: 'trial', nodes: [trigger('customers/create'), wait('wait', 3_600_000, 'action'), action('email', { templateId: 'welcome-customer', maxRecipients: 1 })] },
  { id: 'vip-tagging', name: 'VIP Customer Tagging', description: 'Tag customers whose order exceeds your chosen threshold.', category: 'Customer', impact: 'Enables reliable VIP segmentation.', complexity: 'Simple', minimumPlan: 'trial', nodes: [trigger('orders/create'), condition('order.total', 'greater_than', 200), action('tag_customer', { tag: 'VIP', operation: 'add' }), notify()] },
  { id: 'high-value-order', name: 'High-Value Order Alert', description: 'Notify your team when an order exceeds a chosen value.', category: 'Operations', impact: 'Keeps important orders visible to your team.', complexity: 'Simple', minimumPlan: 'trial', nodes: [trigger('orders/create'), condition('order.total', 'greater_than', 500), action('internal_notification', { message: 'A high-value order needs attention.' }), notify()] },
  { id: 'low-stock-alert', name: 'Low-Stock Internal Alert', description: 'Notify the merchant when available inventory drops below a threshold.', category: 'Inventory', impact: 'Helps teams respond to stock risk earlier.', complexity: 'Simple', minimumPlan: 'trial', nodes: [trigger('inventory_levels/update'), condition('inventory.available', 'less_than', 10), action('internal_notification', { message: 'Inventory is below the configured threshold.' }), notify()] },
  { id: 'post-purchase-thanks', name: 'Post-Purchase Thank You', description: 'Send a thank-you message after a new order.', category: 'Customer', impact: 'Builds a consistent post-purchase experience.', complexity: 'Simple', minimumPlan: 'trial', nodes: [trigger('orders/create'), { id: 'condition', type: 'condition', config: { field: 'order.id', operator: 'exists', value: true }, next: ['wait', 'notify'] }, wait('wait', 7_200_000, 'action'), action('email', { templateId: 'post-purchase-thanks', maxRecipients: 1 }), notify()] },
  { id: 'abandoned-checkout', name: 'Abandoned Checkout Recovery', description: 'Wait before sending a consent-aware checkout reminder.', category: 'Marketing', impact: 'Creates a timely path back to an unfinished checkout.', complexity: 'Medium', minimumPlan: 'start', nodes: [trigger('checkouts/create'), condition('checkout.completed', 'equals', false, 'wait', 'notify'), wait('wait', 3_600_000, 'action'), action('email', { templateId: 'abandoned-checkout', maxRecipients: 1 }), notify()] },
  { id: 'review-request', name: 'Post-Fulfillment Review Request', description: 'Request feedback several days after fulfillment.', category: 'Marketing', impact: 'Encourages authentic product feedback.', complexity: 'Medium', minimumPlan: 'start', nodes: [trigger('orders/updated'), condition('order.fulfillment_status', 'equals', 'fulfilled', 'wait', 'notify'), wait('wait', 432_000_000, 'action'), action('email', { templateId: 'review-request', maxRecipients: 1 }), notify()] },
  { id: 'first-purchase-follow-up', name: 'First-Purchase Follow-Up', description: 'Follow up after a customer’s first order.', category: 'Marketing', impact: 'Supports a thoughtful new-customer journey.', complexity: 'Medium', minimumPlan: 'start', nodes: [trigger('orders/create'), condition('customer.order_count', 'equals', 1, 'wait', 'notify'), wait('wait', 259_200_000, 'action'), action('email', { templateId: 'first-purchase-follow-up', maxRecipients: 1 }), notify()] },
  { id: 'win-back', name: 'Win-Back Inactive Customers', description: 'Review eligible inactive customers on a weekly schedule.', category: 'Revenue', impact: 'Creates a repeatable retention process.', complexity: 'Advanced', minimumPlan: 'growth', nodes: [trigger('cron:0 9 * * 1'), condition('customer.days_since_order', 'greater_than', 90), action('email', { templateId: 'win-back', maxRecipients: 100 }), notify()] },
  { id: 'repeat-purchase', name: 'Repeat Purchase Reminder', description: 'Check daily for established customers ready for a reminder.', category: 'Revenue', impact: 'Supports repeat-purchase engagement.', complexity: 'Advanced', minimumPlan: 'growth', nodes: [trigger('cron:0 10 * * *'), condition('customer.days_since_order', 'between', '30,60'), action('email', { templateId: 'repeat-purchase', maxRecipients: 100 }), notify()] },
  { id: 'back-in-stock', name: 'Back-in-Stock Notification', description: 'Notify eligible customers when inventory returns.', category: 'Revenue', impact: 'Reconnects available inventory with recorded demand.', complexity: 'Advanced', minimumPlan: 'growth', nodes: [trigger('inventory_levels/update'), condition('inventory.previous_available', 'equals', 0), action('email', { templateId: 'back-in-stock', maxRecipients: 100 }), notify()] },
  { id: 'ai-segmentation', name: 'AI-Powered Customer Segmentation', description: 'Classify eligible customers into governed lifecycle segments.', category: 'Customer', impact: 'Supports more relevant customer journeys.', complexity: 'Advanced', minimumPlan: 'commander', nodes: [trigger('cron:0 8 * * 1'), condition('customer.id', 'exists', true, 'ai', 'notify'), { id: 'ai', type: 'ai', config: { operation: 'classify_customer' }, next: ['action'] }, action('tag_customer', { tag: 'AI Segment', operation: 'add' }), notify()] },
  { id: 'smart-discount', name: 'Smart Discount Generator', description: 'Recommend a bounded discount and require merchant approval before creation.', category: 'Revenue', impact: 'Applies governed discount decisions consistently.', complexity: 'Advanced', minimumPlan: 'commander', nodes: [trigger('manual'), { id: 'action', type: 'ai', config: { operation: 'recommend_discount' }, next: ['discount'] }, action('create_discount', { amount: 10, usageLimit: 100, discountType: 'percentage' }, 'discount')] },
  { id: 'slow-moving-promotion', name: 'Slow-Moving Inventory Promotion', description: 'Review slow-moving inventory and prepare a bounded promotion.', category: 'Inventory', impact: 'Helps teams act on aging inventory with oversight.', complexity: 'Advanced', minimumPlan: 'commander', nodes: [trigger('cron:0 9 * * 1'), condition('inventory.days_without_sale', 'greater_than', 60, 'ai', 'notify'), { id: 'ai', type: 'ai', config: { operation: 'classify_slow_inventory' }, next: ['action'] }, action('create_discount', { amount: 10, usageLimit: 100, discountType: 'percentage' }), notify()] },
  { id: 'predictive-churn', name: 'Predictive Churn Prevention', description: 'Identify elevated churn risk and prepare a governed retention message.', category: 'Customer', impact: 'Makes retention follow-up more consistent.', complexity: 'Advanced', minimumPlan: 'commander', nodes: [trigger('cron:0 8 * * *'), condition('customer.id', 'exists', true, 'ai', 'notify'), { id: 'ai', type: 'ai', config: { operation: 'predict_churn' }, next: ['action'] }, action('tag_customer', { tag: 'At Risk', operation: 'add' }), notify()] },
]

export function templateFor(id: string): WorkflowTemplate | null { return WORKFLOW_TEMPLATES.find((template) => template.id === id) ?? null }
export function installTemplate(template: WorkflowTemplate, input: Readonly<{ id: string; storeId: string; name: string; actor: string }>): WorkflowDefinition { return { id: input.id, storeId: input.storeId as StoreId, name: input.name.trim(), description: template.description, category: template.category, tags: [], version: 1, nodes: template.nodes, timezone: 'UTC', overlapPolicy: 'SKIP' } }
export function planAllowsTemplate(plan: PlanTier, minimum: PlanTier): boolean { return rank(plan) >= rank(minimum) }
function rank(plan: PlanTier): number { return plan === 'trial' ? 0 : plan === 'start' ? 1 : plan === 'growth' ? 2 : 3 }
